{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-lib-tor/409.13.0-rc1/resource-lib-tor-409.13.0-rc1.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-lib-tor",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-jvm-409.13.0-rc1.jar",
          "url": "resource-lib-tor-jvm-409.13.0-rc1.jar",
          "size": 62110556,
          "sha512": "58c6fdbe83a8d58cf61d17271e9f0379c3b1c5bb35419544189382432261094bcd50500995c00188c4e7c2b8211459156d1c4e68d2ddbd0e266369bb49162f0d",
          "sha256": "892b592ded5fa6e20a63d98b4161a68d4fbd281ac6ccae29f45c75901382e927",
          "sha1": "223265205d645f579948b012ebc95c42b66d7428",
          "md5": "5062e8458f0b6dbc6118c04aab57da26"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-jvm-409.13.0-rc1.jar",
          "url": "resource-lib-tor-jvm-409.13.0-rc1.jar",
          "size": 62110556,
          "sha512": "58c6fdbe83a8d58cf61d17271e9f0379c3b1c5bb35419544189382432261094bcd50500995c00188c4e7c2b8211459156d1c4e68d2ddbd0e266369bb49162f0d",
          "sha256": "892b592ded5fa6e20a63d98b4161a68d4fbd281ac6ccae29f45c75901382e927",
          "sha1": "223265205d645f579948b012ebc95c42b66d7428",
          "md5": "5062e8458f0b6dbc6118c04aab57da26"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "resource-lib-tor-jvm-409.13.0-rc1-sources.jar",
          "url": "resource-lib-tor-jvm-409.13.0-rc1-sources.jar",
          "size": 7603,
          "sha512": "ea3617cd852634643ca9644b8688f1b42e60c345d90b782ae189b2ec2ee25248f7cddcee7018708540373c67f39fc06976675c5ecbb1aaa5fd83b2fb056ac4da",
          "sha256": "037c5ef8650245eb35c1e0c18a433b5fc137422a1ed71e16a2e1e10165658e0a",
          "sha1": "b79d24163b9342df427a0963409c8c84b7fdb3d4",
          "md5": "621656b990811d80d5ec7421f32df69a"
        }
      ]
    }
  ]
}
