{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-compilation-lib-tor/409.12.0-SNAPSHOT/resource-compilation-lib-tor-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-compilation-lib-tor",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-compilation-lib-tor-release.aar",
          "url": "resource-compilation-lib-tor-android-409.12.0-SNAPSHOT.aar",
          "size": 14724316,
          "sha512": "9ceccb13358897ac32d49d04f22a2fb857c188246157dff0ffe7df86eb1c90c47fe3e273560ea5f70c808c9bff6bc19c180f3d78b53b19e39bfb1dc409b74b7d",
          "sha256": "3d6f300d8ed20d461f93b2d46a288466185a724f301538a4db3790dfc5ebc412",
          "sha1": "0dfc03c45a654c6043e62cef7423ccffbaf20c21",
          "md5": "6200adfb4d6e7b87e4db8531ad6ca8a5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-compilation-lib-tor-release.aar",
          "url": "resource-compilation-lib-tor-android-409.12.0-SNAPSHOT.aar",
          "size": 14724316,
          "sha512": "9ceccb13358897ac32d49d04f22a2fb857c188246157dff0ffe7df86eb1c90c47fe3e273560ea5f70c808c9bff6bc19c180f3d78b53b19e39bfb1dc409b74b7d",
          "sha256": "3d6f300d8ed20d461f93b2d46a288466185a724f301538a4db3790dfc5ebc412",
          "sha1": "0dfc03c45a654c6043e62cef7423ccffbaf20c21",
          "md5": "6200adfb4d6e7b87e4db8531ad6ca8a5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-compilation-lib-tor-android-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-compilation-lib-tor-android-409.12.0-SNAPSHOT-sources.jar",
          "size": 4033,
          "sha512": "ab98f035bebbfece927f889039fa5562cc31284547a722630244ba66f0133e8a6bbf184130ce616afd6ed3c71921e34658060cb3acad419f763d8319c5a3fb48",
          "sha256": "84ed2d37f9acd2fb20d8569eb4eaf3efdec16833ec0949ec54a37b9972097d0b",
          "sha1": "2afd79f162572ddfecb3d63627bab20f41ba3d3e",
          "md5": "b30d4ff64bd0b7b7fc7ac149264458e1"
        }
      ]
    }
  ]
}
