{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-android-unit-test-tor/409.13.0-SNAPSHOT/resource-android-unit-test-tor-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-android-unit-test-tor",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-android-unit-test-tor-release.aar",
          "url": "resource-android-unit-test-tor-android-409.13.0-SNAPSHOT.aar",
          "size": 62316296,
          "sha512": "0a23edca6abad23e08071157a84a7fb59f90f328e7aa97c3d48c8b2673c38b2e869db5edb9d854bc5fac9bd280cd6900b9e8658373267added09876ff163e3e4",
          "sha256": "0b976a7f813c520252862d75033606174f8cbffa96b92adc000d3adb85776d6f",
          "sha1": "b4335da66502164f3d776a33cca6724f33e3e21f",
          "md5": "cc8eac4d57632d049cc0bf84a386b8c1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-android-unit-test-tor-release.aar",
          "url": "resource-android-unit-test-tor-android-409.13.0-SNAPSHOT.aar",
          "size": 62316296,
          "sha512": "0a23edca6abad23e08071157a84a7fb59f90f328e7aa97c3d48c8b2673c38b2e869db5edb9d854bc5fac9bd280cd6900b9e8658373267added09876ff163e3e4",
          "sha256": "0b976a7f813c520252862d75033606174f8cbffa96b92adc000d3adb85776d6f",
          "sha1": "b4335da66502164f3d776a33cca6724f33e3e21f",
          "md5": "cc8eac4d57632d049cc0bf84a386b8c1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-android-unit-test-tor-android-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-android-unit-test-tor-android-409.13.0-SNAPSHOT-sources.jar",
          "size": 2635,
          "sha512": "a1ee7f658f0314d0c2f5eac5fe77278e617f7ba233f888316a7843254b0e66eee171e68b4c426657a1c9dd3a5d8fb1d6c945811285af35ebb8a7fe4197533ee7",
          "sha256": "49113d5c3ae39ba080c49a8b6a0cb8bf0dfb9f6cb10df6d95892b83a1b380750",
          "sha1": "b0362b4dcbaa0b6dd486d1bc571586572e0a6569",
          "md5": "a01342f64298435e56d85bfea1f43da5"
        }
      ]
    }
  ]
}
