{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-lib-tor/409.12.0-SNAPSHOT/resource-lib-tor-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-lib-tor",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-jvm-409.12.0-SNAPSHOT.jar",
          "url": "resource-lib-tor-jvm-409.12.0-SNAPSHOT.jar",
          "size": 62084242,
          "sha512": "319bdb97ac532ad3cccf80d91d24b235a7dd89acdcf580f96db4cd7cdbc2307dafaa82aa83c36094939fdf08ff7bcc8ad753eeb85a49ccbd4d205ad2140d3f8e",
          "sha256": "275fcb876fc2d751fc41b32a0e9d4688c2f6950c92a4f309c8bfbc37e887e332",
          "sha1": "bf2bf8d915db6d283b42e0869ab128c2a4de769d",
          "md5": "c928b67f1bb40667d80eca4768c12ece"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-jvm-409.12.0-SNAPSHOT.jar",
          "url": "resource-lib-tor-jvm-409.12.0-SNAPSHOT.jar",
          "size": 62084242,
          "sha512": "319bdb97ac532ad3cccf80d91d24b235a7dd89acdcf580f96db4cd7cdbc2307dafaa82aa83c36094939fdf08ff7bcc8ad753eeb85a49ccbd4d205ad2140d3f8e",
          "sha256": "275fcb876fc2d751fc41b32a0e9d4688c2f6950c92a4f309c8bfbc37e887e332",
          "sha1": "bf2bf8d915db6d283b42e0869ab128c2a4de769d",
          "md5": "c928b67f1bb40667d80eca4768c12ece"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "resource-lib-tor-jvm-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-lib-tor-jvm-409.12.0-SNAPSHOT-sources.jar",
          "size": 7603,
          "sha512": "ea3617cd852634643ca9644b8688f1b42e60c345d90b782ae189b2ec2ee25248f7cddcee7018708540373c67f39fc06976675c5ecbb1aaa5fd83b2fb056ac4da",
          "sha256": "037c5ef8650245eb35c1e0c18a433b5fc137422a1ed71e16a2e1e10165658e0a",
          "sha1": "b79d24163b9342df427a0963409c8c84b7fdb3d4",
          "md5": "621656b990811d80d5ec7421f32df69a"
        }
      ]
    }
  ]
}
