{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-lib-tor/409.12.0-SNAPSHOT/resource-lib-tor-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-lib-tor",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-jvm-409.12.0-SNAPSHOT.jar",
          "url": "resource-lib-tor-jvm-409.12.0-SNAPSHOT.jar",
          "size": 61936790,
          "sha512": "4f637ddf47e71ec16a0659111a0b5941a27e23f8d9854fac8e7cf70fa715162789ca0752493914a2be7f01f04ed4383282e5d928b7801fbfdad2707cfd895036",
          "sha256": "1dbe5e7db76597b3bd227be4e164c0773d98c2cebb9bfd040c7b6956a4ac81da",
          "sha1": "36f47924709bbd988bd5a5778b6f493dc62485be",
          "md5": "2c04f01ba532d378173571de70856fbf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-jvm-409.12.0-SNAPSHOT.jar",
          "url": "resource-lib-tor-jvm-409.12.0-SNAPSHOT.jar",
          "size": 61936790,
          "sha512": "4f637ddf47e71ec16a0659111a0b5941a27e23f8d9854fac8e7cf70fa715162789ca0752493914a2be7f01f04ed4383282e5d928b7801fbfdad2707cfd895036",
          "sha256": "1dbe5e7db76597b3bd227be4e164c0773d98c2cebb9bfd040c7b6956a4ac81da",
          "sha1": "36f47924709bbd988bd5a5778b6f493dc62485be",
          "md5": "2c04f01ba532d378173571de70856fbf"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "resource-lib-tor-jvm-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-lib-tor-jvm-409.12.0-SNAPSHOT-sources.jar",
          "size": 7603,
          "sha512": "ea3617cd852634643ca9644b8688f1b42e60c345d90b782ae189b2ec2ee25248f7cddcee7018708540373c67f39fc06976675c5ecbb1aaa5fd83b2fb056ac4da",
          "sha256": "037c5ef8650245eb35c1e0c18a433b5fc137422a1ed71e16a2e1e10165658e0a",
          "sha1": "b79d24163b9342df427a0963409c8c84b7fdb3d4",
          "md5": "621656b990811d80d5ec7421f32df69a"
        }
      ]
    }
  ]
}
