{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor-gpl/409.13.0-rc1/resource-exec-tor-gpl-409.13.0-rc1.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-exec-tor-gpl",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-iosArm64Main-409.13.0-rc1.klib",
          "url": "resource-exec-tor-gpl-iosarm64-409.13.0-rc1.klib",
          "size": 11005,
          "sha512": "fce0ba7b849eeef51613fa8cabe3989a3f3868aec240d3210e0c744a6450142cf9868753a0b5d4ea5bd0d2b0a3a127d7d999d27183994f75a152a1835166b4d9",
          "sha256": "fae92d65f54b730bd4ac9e51626e06bcf4b4705d7d7dc1a2b4b5d28471cd392b",
          "sha1": "cc217955782052613202ffefe22dfa42a542e451",
          "md5": "aadf4cede3b89e9906edcc2d877ae4ce"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-exec-tor-gpl-iosarm64-409.13.0-rc1-sources.jar",
          "url": "resource-exec-tor-gpl-iosarm64-409.13.0-rc1-sources.jar",
          "size": 6583,
          "sha512": "c672902ffe5b9f28d8e76f0dfd9dd4fe8d2a381f660a30347ead749c5fc23472992292a87a63b9ad0732bc2aa39f1c1692b08a0979843af2db2ada52d6030612",
          "sha256": "af3de202fcd1cef7fd760a62b7de77835b0cddba5b9713bb11f501092155debc",
          "sha1": "0ab8e635b48456d64de623d6a8206730e958cab9",
          "md5": "41d5ad4e86dfb2a4f930f092d1325c02"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-iosarm64-409.13.0-rc1-metadata.jar",
          "url": "resource-exec-tor-gpl-iosarm64-409.13.0-rc1-metadata.jar",
          "size": 6755,
          "sha512": "496bf7065f3de02afd7ccacfd2674a77de455f8a04aff43c96f502c1328a408e3104df7ca8ca628984f3e05d598e5760262e9dc84a30ed3b54bc76ae0f5d58c1",
          "sha256": "3a80eccfe83a21522d44bbb9df5bda518b036cc219b7cc458a3f6585d2d9a9a3",
          "sha1": "f427537d6e2e77e9b120095493cb8de2f28c3a6b",
          "md5": "bee141be3a1c35977699c6567c615896"
        }
      ]
    }
  ]
}
