{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor-gpl/409.13.0/resource-exec-tor-gpl-409.13.0.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-exec-tor-gpl",
    "version": "409.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-androidNativeArm32Main-409.13.0.klib",
          "url": "resource-exec-tor-gpl-androidnativearm32-409.13.0.klib",
          "size": 23814,
          "sha512": "8c1342a8d8b0d90cd3c8bbe34aab77abfb2e54b86287ddd63e730bfaae60d19f0a2b3fbaaf510c1553b2518f86b46b0d26525065fc445e259baaec66306c9cc9",
          "sha256": "4dae1bb750d8b57360bc7a70f32bcc3b794c857ee792322259805294c65af43c",
          "sha1": "02d1146001dcf5fbf3c8b6b56e6b06fa380d3f00",
          "md5": "98f4b1264c2fe9b5b3b9b5062e611b98"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-exec-tor-gpl-androidnativearm32-409.13.0-sources.jar",
          "url": "resource-exec-tor-gpl-androidnativearm32-409.13.0-sources.jar",
          "size": 11711,
          "sha512": "cbc9c98a2eec49e576023f221a4c64d2f8c41624fcb727e3821163f3e5da98ec60b90ad2227c2e99798e7795ebf4859c35c3009463b1d4e97d3f7f08535af115",
          "sha256": "be928b9f248c958477cc8bc557a5c91a7da67ad01280376547e693aef6708a38",
          "sha1": "d06d3b8f277c27c1fb3689e5dc0e2f3cbc68893c",
          "md5": "f87f6530ffcc3e90e4e2a856c1ceb3cd"
        }
      ]
    }
  ]
}
