{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-compilation-lib-tor/409.13.0-SNAPSHOT/resource-compilation-lib-tor-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-compilation-lib-tor",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-compilation-lib-tor-release.aar",
          "url": "resource-compilation-lib-tor-android-409.13.0-SNAPSHOT.aar",
          "size": 14730522,
          "sha512": "a54b7442a2da43d48d4e9c7e8df5a2515ef6dc8270f4bb04c218bc46eec855712ca90df3a36041248ae9b6f609b67385dd0e1418a79960754e0a0751bb362170",
          "sha256": "375851a44da9d93e8feb859f6c2edc091164cf3c63a89e98f821caf48a965e36",
          "sha1": "73ab1839e7d6f07b66d187f96ec68efe79e19673",
          "md5": "8b1b5aa14b381e6128e712b8e40681a5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-compilation-lib-tor-release.aar",
          "url": "resource-compilation-lib-tor-android-409.13.0-SNAPSHOT.aar",
          "size": 14730522,
          "sha512": "a54b7442a2da43d48d4e9c7e8df5a2515ef6dc8270f4bb04c218bc46eec855712ca90df3a36041248ae9b6f609b67385dd0e1418a79960754e0a0751bb362170",
          "sha256": "375851a44da9d93e8feb859f6c2edc091164cf3c63a89e98f821caf48a965e36",
          "sha1": "73ab1839e7d6f07b66d187f96ec68efe79e19673",
          "md5": "8b1b5aa14b381e6128e712b8e40681a5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-compilation-lib-tor-android-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-compilation-lib-tor-android-409.13.0-SNAPSHOT-sources.jar",
          "size": 4033,
          "sha512": "ab98f035bebbfece927f889039fa5562cc31284547a722630244ba66f0133e8a6bbf184130ce616afd6ed3c71921e34658060cb3acad419f763d8319c5a3fb48",
          "sha256": "84ed2d37f9acd2fb20d8569eb4eaf3efdec16833ec0949ec54a37b9972097d0b",
          "sha1": "2afd79f162572ddfecb3d63627bab20f41ba3d3e",
          "md5": "b30d4ff64bd0b7b7fc7ac149264458e1"
        }
      ]
    }
  ]
}
