{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-lib-tor-gpl/409.12.0-SNAPSHOT/resource-lib-tor-gpl-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-lib-tor-gpl",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-gpl-jvm-409.12.0-SNAPSHOT.jar",
          "url": "resource-lib-tor-gpl-jvm-409.12.0-SNAPSHOT.jar",
          "size": 62506479,
          "sha512": "8f97b6a0febb6ea26827d47331a42e19fb4caf7595ee7a445277396fe5df0ff17c0c13c7e8866e786138d1cde7338c7060c52bc2be8ecadb3137be5aef3b742f",
          "sha256": "cad1e2caca3b6a4f2168be8ec3063a16bc242e4226f86fdb7ccd8121d2e3a4bb",
          "sha1": "b4b75dd8f9592b2e7f94d92ecec6a571af562ef9",
          "md5": "a94b8347ab1b55b2bf3455816a4a39f0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-gpl-jvm-409.12.0-SNAPSHOT.jar",
          "url": "resource-lib-tor-gpl-jvm-409.12.0-SNAPSHOT.jar",
          "size": 62506479,
          "sha512": "8f97b6a0febb6ea26827d47331a42e19fb4caf7595ee7a445277396fe5df0ff17c0c13c7e8866e786138d1cde7338c7060c52bc2be8ecadb3137be5aef3b742f",
          "sha256": "cad1e2caca3b6a4f2168be8ec3063a16bc242e4226f86fdb7ccd8121d2e3a4bb",
          "sha1": "b4b75dd8f9592b2e7f94d92ecec6a571af562ef9",
          "md5": "a94b8347ab1b55b2bf3455816a4a39f0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "resource-lib-tor-gpl-jvm-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-lib-tor-gpl-jvm-409.12.0-SNAPSHOT-sources.jar",
          "size": 7603,
          "sha512": "ea3617cd852634643ca9644b8688f1b42e60c345d90b782ae189b2ec2ee25248f7cddcee7018708540373c67f39fc06976675c5ecbb1aaa5fd83b2fb056ac4da",
          "sha256": "037c5ef8650245eb35c1e0c18a433b5fc137422a1ed71e16a2e1e10165658e0a",
          "sha1": "b79d24163b9342df427a0963409c8c84b7fdb3d4",
          "md5": "621656b990811d80d5ec7421f32df69a"
        }
      ]
    }
  ]
}
