{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-noexec-tor",
    "version": "409.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-metadata-409.13.0.jar",
          "url": "resource-noexec-tor-409.13.0.jar",
          "size": 82796,
          "sha512": "c96dde06a5b555e5fdeae9063569a96b58682067ba894ad1f6557d96c0f542c5008156298b5af700dbd7f2ce436ffddcd8243229d1fff6d47ca1711461bfce62",
          "sha256": "e3a72afd3989b144729fdfacdc6b19b49717b53ba1009031b767fe288c96ccae",
          "sha1": "8b183ef9fd3dde90c0ffc8495885912efdab5517",
          "md5": "a5dd5ca95d760ba730446eda18fa2d69"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "resource-noexec-tor-kotlin-409.13.0-sources.jar",
          "url": "resource-noexec-tor-409.13.0-sources.jar",
          "size": 23385,
          "sha512": "90ede255198a58af71b3facd0c347e128d00fa7739452aa273e5a83f066185c39504edaa9c6bb5dd85cd810e51af9c30bc4d094567384b34821701141e98ef82",
          "sha256": "bbda61f84c88a5cfef0072cf5a62e1d511f67af57799a60c9005e9c2e0ab328a",
          "sha1": "d8174080f0cae2ead517389751c38095b1c2cf7c",
          "md5": "42f4e3d73653ac483d3007208c9f2158"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-android/409.13.0/resource-noexec-tor-android-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-android",
        "version": "409.13.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-android/409.13.0/resource-noexec-tor-android-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-android",
        "version": "409.13.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-android/409.13.0/resource-noexec-tor-android-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-android",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-androidnativearm32/409.13.0/resource-noexec-tor-androidnativearm32-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-androidnativearm32",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-androidnativearm32/409.13.0/resource-noexec-tor-androidnativearm32-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-androidnativearm32",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-androidnativearm64/409.13.0/resource-noexec-tor-androidnativearm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-androidnativearm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-androidnativearm64/409.13.0/resource-noexec-tor-androidnativearm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-androidnativearm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-androidnativex64/409.13.0/resource-noexec-tor-androidnativex64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-androidnativex64",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-androidnativex64/409.13.0/resource-noexec-tor-androidnativex64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-androidnativex64",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-androidnativex86/409.13.0/resource-noexec-tor-androidnativex86-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-androidnativex86",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-androidnativex86/409.13.0/resource-noexec-tor-androidnativex86-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-androidnativex86",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-iosarm64/409.13.0/resource-noexec-tor-iosarm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-iosarm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-iosarm64/409.13.0/resource-noexec-tor-iosarm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-iosarm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-iosarm64/409.13.0/resource-noexec-tor-iosarm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-iosarm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-iossimulatorarm64/409.13.0/resource-noexec-tor-iossimulatorarm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-iossimulatorarm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-iossimulatorarm64/409.13.0/resource-noexec-tor-iossimulatorarm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-iossimulatorarm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-iossimulatorarm64/409.13.0/resource-noexec-tor-iossimulatorarm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-iossimulatorarm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-iosx64/409.13.0/resource-noexec-tor-iosx64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-iosx64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-iosx64/409.13.0/resource-noexec-tor-iosx64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-iosx64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-iosx64/409.13.0/resource-noexec-tor-iosx64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-iosx64",
        "version": "409.13.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-jvm/409.13.0/resource-noexec-tor-jvm-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-jvm",
        "version": "409.13.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-jvm/409.13.0/resource-noexec-tor-jvm-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-jvm",
        "version": "409.13.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-noexec-tor-jvm/409.13.0/resource-noexec-tor-jvm-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-noexec-tor-jvm",
        "version": "409.13.0"
      }
    }
  ]
}
