{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-noexec-tor/409.13.0-SNAPSHOT/resource-noexec-tor-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-noexec-tor",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-jvm-409.13.0-SNAPSHOT.jar",
          "url": "resource-noexec-tor-jvm-409.13.0-SNAPSHOT.jar",
          "size": 221156,
          "sha512": "46c34209d0b2d2c30493fa905969e64964c5eb6fb5591e5feba398cf273927bbcc242f89e498b6e1582ff00315daa55238ea6bcef6094fb686ba7ff5c9c0b076",
          "sha256": "9226479ac864e0f94d4c0d7dc8d9068fd9098131f9ec0a8e2c2f8755e5fc6f33",
          "sha1": "23ffac7888f0bbff7c5e0392ae51ade757ece486",
          "md5": "a1c2021be94ab422227714e70ed030a8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-lib-tor",
          "version": {
            "requires": "409.13.0-SNAPSHOT"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-jvm-409.13.0-SNAPSHOT.jar",
          "url": "resource-noexec-tor-jvm-409.13.0-SNAPSHOT.jar",
          "size": 221156,
          "sha512": "46c34209d0b2d2c30493fa905969e64964c5eb6fb5591e5feba398cf273927bbcc242f89e498b6e1582ff00315daa55238ea6bcef6094fb686ba7ff5c9c0b076",
          "sha256": "9226479ac864e0f94d4c0d7dc8d9068fd9098131f9ec0a8e2c2f8755e5fc6f33",
          "sha1": "23ffac7888f0bbff7c5e0392ae51ade757ece486",
          "md5": "a1c2021be94ab422227714e70ed030a8"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "resource-noexec-tor-jvm-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-noexec-tor-jvm-409.13.0-SNAPSHOT-sources.jar",
          "size": 16079,
          "sha512": "8e1a4272f0ac4f36151ef9845ff6af6193eeb4fe9d19aed414cf8d8e5fc74f798ab8af0fd9799030ae3032af03014c7f1bec68c299656afa6f96b694fc6f4c00",
          "sha256": "f423691ca5669067c376262f1dd56bf5b576bef88f3d84b20526347e4e825e6c",
          "sha1": "392a988d76375a1bcb9decbc99922b8b95f009de",
          "md5": "d6538bbd34cb0d58004fedc3cf1e6cc0"
        }
      ]
    }
  ]
}
