{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor/409.13.0-SNAPSHOT/resource-exec-tor-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-exec-tor",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-jvm-409.13.0-SNAPSHOT.jar",
          "url": "resource-exec-tor-jvm-409.13.0-SNAPSHOT.jar",
          "size": 67189,
          "sha512": "22509828e2f50c280ae71d83b027bf9ccdbd75059f18cf2c016658f932245137e851389bc5aa484891d95fdf25315cc701ea094f361142dea9cf8a74f88bd789",
          "sha256": "8dacbb7ab74dc911ee33fa621c5dcd766379d430b98a502d5a0c7e45c5d1cf50",
          "sha1": "d44510a87797cf765b1667ffa7def9bd1270f148",
          "md5": "c7fc169023895fe1903d1add3ffe55d4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-lib-tor",
          "version": {
            "requires": "409.13.0-SNAPSHOT"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-jvm-409.13.0-SNAPSHOT.jar",
          "url": "resource-exec-tor-jvm-409.13.0-SNAPSHOT.jar",
          "size": 67189,
          "sha512": "22509828e2f50c280ae71d83b027bf9ccdbd75059f18cf2c016658f932245137e851389bc5aa484891d95fdf25315cc701ea094f361142dea9cf8a74f88bd789",
          "sha256": "8dacbb7ab74dc911ee33fa621c5dcd766379d430b98a502d5a0c7e45c5d1cf50",
          "sha1": "d44510a87797cf765b1667ffa7def9bd1270f148",
          "md5": "c7fc169023895fe1903d1add3ffe55d4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "resource-exec-tor-jvm-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-exec-tor-jvm-409.13.0-SNAPSHOT-sources.jar",
          "size": 12121,
          "sha512": "37f56e8ec8bda4a5d3fb737f7e7889218e6000299324f3ca9374b0c3a042a5b2a86a70b40640409b43af7cc26ff01964c880d108d22603f0ab7058d354111e91",
          "sha256": "9f273b5fbafbbca216e24d76707f6d2bc5068e9a54e21e2938f6aa3207350199",
          "sha1": "754bd1ba103cb909705d2dc3125014c9332c8935",
          "md5": "ae7996defa2e35f088ebdb28369bbb2a"
        }
      ]
    }
  ]
}
