{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-noexec-tor-gpl/409.13.0-SNAPSHOT/resource-noexec-tor-gpl-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-noexec-tor-gpl",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-gpl-androidNativeX64Main-409.13.0-SNAPSHOT.klib",
          "url": "resource-noexec-tor-gpl-androidnativex64-409.13.0-SNAPSHOT.klib",
          "size": 39367,
          "sha512": "526530597a01ea65a330974695004aa1a07655c6f62fc833f758a331d8cff70e561fd8d51e5328582a29bae5bffc60d1670b8f4dca08e933c3ba8aaff9fdb58e",
          "sha256": "e4f554040ff7194ade351971f37fe1fff843b2c0d0dc086ba7e8f4e31e9a77e5",
          "sha1": "f3ae6dcbd7c1206541d205d77416f29d5587c426",
          "md5": "5f212d4211813fa2432ee4e73e9d8c5d"
        },
        {
          "name": "resource-noexec-tor-gpl-androidNativeX64Cinterop-kmp_torMain-409.13.0-SNAPSHOT.klib",
          "url": "resource-noexec-tor-gpl-androidnativex64-409.13.0-SNAPSHOT-cinterop-kmp_tor.klib",
          "size": 10840,
          "sha512": "ff63a5865fd1c7521831c574495a1b20453e65a004f36027ec49b1c289f7b55c49a853055ac618c569f287a3133efe6f17eff8290c3ef95863d4bcded91d1a14",
          "sha256": "4ac44a508635bb62002844538ab48fcac647929c4edbf28a4d016d52d36ab91a",
          "sha1": "f7be88e11bd9bdca358e4f874ae7cb6b07e92c6a",
          "md5": "3c576d7a201592699129de290da95462"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-noexec-tor-gpl-androidnativex64-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-noexec-tor-gpl-androidnativex64-409.13.0-SNAPSHOT-sources.jar",
          "size": 17943,
          "sha512": "3d9a2268373d438c85a1c390b717ee373ba725c96f04b9ecde0fe7da13cdadc1b6bae321b8c2c23e9ca915b7be60dd0ece6def83a1548a3c3a9f2d3878ced672",
          "sha256": "13dbc89eedba1e9bbf68293d732d428c835f62cd47691f4b033eec7885a8d319",
          "sha1": "6c5742af4d5c4226c875f2734135a5049454f21c",
          "md5": "37bcd6b4c4972a89a3c0566134788604"
        }
      ]
    }
  ]
}
