{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-noexec-tor-gpl/409.13.0-rc1/resource-noexec-tor-gpl-409.13.0-rc1.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-noexec-tor-gpl",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-gpl-release.aar",
          "url": "resource-noexec-tor-gpl-android-409.13.0-rc1.aar",
          "size": 54003,
          "sha512": "f9d380cd6673ef701ba5eca358821d85a818f16f2a3d1280a3640fb618b9af1c02902b600202cae3fdf40fdd7734f681b046ad54aecc8a1e17c9d39a75bb6101",
          "sha256": "56766b728b6a6352d03f77d7412c64c8cae5b104ae614c62791b3515b56cd7ac",
          "sha1": "485ba79ba0cdf588e5d6d5d353e5855a1967e9fb",
          "md5": "0c8270a030d6326b962fe807cd8065d9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-lib-tor-gpl",
          "version": {
            "requires": "409.13.0-rc1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0-rc1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-gpl-release.aar",
          "url": "resource-noexec-tor-gpl-android-409.13.0-rc1.aar",
          "size": 54003,
          "sha512": "f9d380cd6673ef701ba5eca358821d85a818f16f2a3d1280a3640fb618b9af1c02902b600202cae3fdf40fdd7734f681b046ad54aecc8a1e17c9d39a75bb6101",
          "sha256": "56766b728b6a6352d03f77d7412c64c8cae5b104ae614c62791b3515b56cd7ac",
          "sha1": "485ba79ba0cdf588e5d6d5d353e5855a1967e9fb",
          "md5": "0c8270a030d6326b962fe807cd8065d9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-noexec-tor-gpl-android-409.13.0-rc1-sources.jar",
          "url": "resource-noexec-tor-gpl-android-409.13.0-rc1-sources.jar",
          "size": 17291,
          "sha512": "0d2d40b1cce34e1aa72e6c08cd205f9cb52d48cf6bb9b766349794979b1f786ace22ae2b02a1bab5d43d28fba638dca2b34997512d8b83fbff66d26b39b254f6",
          "sha256": "0c5367cd4f29c0257e07adca0fe13dbe1f4494c032ae2a0790c9bef12bd07c25",
          "sha1": "21394573ca9475ca430d6ef4a5da5c2978a02523",
          "md5": "0ee764f4d73e5c57b740ffddf72fcb23"
        }
      ]
    }
  ]
}
