{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor/409.13.0-rc1/resource-exec-tor-409.13.0-rc1.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-exec-tor",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-jvm-409.13.0-rc1.jar",
          "url": "resource-exec-tor-jvm-409.13.0-rc1.jar",
          "size": 67212,
          "sha512": "213ac1c6198dfba6043bd44be93e3a1f0b60c9a270b4ec2cda5bc69d3a4d092ebbf730afb025f3dc34ec587516bb5e16c7af18ba9ff5817b9f98c0e6027bab21",
          "sha256": "e02b7c46ff1a6666269bd4bf2e904bbf22a5f81c4be7706e7b68d7559d7b6f1a",
          "sha1": "f03e39a18901d43288e474f470bf622072fa1edb",
          "md5": "8ec4035fdbc1443044e0cf18f0790026"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-lib-tor",
          "version": {
            "requires": "409.13.0-rc1"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-jvm-409.13.0-rc1.jar",
          "url": "resource-exec-tor-jvm-409.13.0-rc1.jar",
          "size": 67212,
          "sha512": "213ac1c6198dfba6043bd44be93e3a1f0b60c9a270b4ec2cda5bc69d3a4d092ebbf730afb025f3dc34ec587516bb5e16c7af18ba9ff5817b9f98c0e6027bab21",
          "sha256": "e02b7c46ff1a6666269bd4bf2e904bbf22a5f81c4be7706e7b68d7559d7b6f1a",
          "sha1": "f03e39a18901d43288e474f470bf622072fa1edb",
          "md5": "8ec4035fdbc1443044e0cf18f0790026"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "resource-exec-tor-jvm-409.13.0-rc1-sources.jar",
          "url": "resource-exec-tor-jvm-409.13.0-rc1-sources.jar",
          "size": 12121,
          "sha512": "37f56e8ec8bda4a5d3fb737f7e7889218e6000299324f3ca9374b0c3a042a5b2a86a70b40640409b43af7cc26ff01964c880d108d22603f0ab7058d354111e91",
          "sha256": "9f273b5fbafbbca216e24d76707f6d2bc5068e9a54e21e2938f6aa3207350199",
          "sha1": "754bd1ba103cb909705d2dc3125014c9332c8935",
          "md5": "ae7996defa2e35f088ebdb28369bbb2a"
        }
      ]
    }
  ]
}
