{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor-gpl/409.13.0/resource-exec-tor-gpl-409.13.0.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-exec-tor-gpl",
    "version": "409.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-release.aar",
          "url": "resource-exec-tor-gpl-android-409.13.0.aar",
          "size": 27068,
          "sha512": "220c3952bc890b5c9f99ba06d7f681983c4f23c448bfb4f54c379ddd95eb2a74e38e6a82efc653e0ff42dab8f11742c2b31b48f5b20454f65dd3b80b7d015204",
          "sha256": "e6054554460c7a3c2f8f9e6e87b20a6a4b3286f3e46c834444851619fe899fc2",
          "sha1": "7fa212c76f117f70a1d610197b7d30464c69bbb9",
          "md5": "208bba230dce18ad4359649d78847609"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-compilation-exec-tor-gpl",
          "version": {
            "requires": "409.13.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-lib-tor-gpl",
          "version": {
            "requires": "409.13.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-release.aar",
          "url": "resource-exec-tor-gpl-android-409.13.0.aar",
          "size": 27068,
          "sha512": "220c3952bc890b5c9f99ba06d7f681983c4f23c448bfb4f54c379ddd95eb2a74e38e6a82efc653e0ff42dab8f11742c2b31b48f5b20454f65dd3b80b7d015204",
          "sha256": "e6054554460c7a3c2f8f9e6e87b20a6a4b3286f3e46c834444851619fe899fc2",
          "sha1": "7fa212c76f117f70a1d610197b7d30464c69bbb9",
          "md5": "208bba230dce18ad4359649d78847609"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-exec-tor-gpl-android-409.13.0-sources.jar",
          "url": "resource-exec-tor-gpl-android-409.13.0-sources.jar",
          "size": 11888,
          "sha512": "70a552dd72adeed548c754e0efc536a289ab83ade8b2e88583f43548fdf9c00e344df32bf82f1fe3be6be5dcf8c055e3913f66b690efece26602e62d68bb1b62",
          "sha256": "b0328adf5d0ce625ee53b75666aa492b3d8ea30ddf88e164cff5227c2297825e",
          "sha1": "12fbc89f8cb1c2080cd81ded1dca94ca000225c0",
          "md5": "23413c4580524284a50d5ce1bce491b5"
        }
      ]
    }
  ]
}
