{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-geoip/409.12.0-SNAPSHOT/resource-geoip-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-geoip",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-geoip-androidNativeX86Main-409.12.0-SNAPSHOT.klib",
          "url": "resource-geoip-androidnativex86-409.12.0-SNAPSHOT.klib",
          "size": 9560421,
          "sha512": "fbffc2cc7588e977d1162caa4f6f9e26d9e10e4048054a5591862a1a9f73be41e418ac68b5c5a6cff64aed72c1b41777fd19509c6ec222b7b0a71648cd187762",
          "sha256": "c6b2a5f3b93b92ed580d8b6a2fd7db1baf817b1a277965501c0254977411b2ef",
          "sha1": "970725ed950f92b8e301e430defbe3944675b2b0",
          "md5": "c00a744796c9ba1c4e29b862b2aaba6b"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-geoip-androidnativex86-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-geoip-androidnativex86-409.12.0-SNAPSHOT-sources.jar",
          "size": 4581362,
          "sha512": "d41ca04f478f47bb5420516873969136141cf3cffe76919c28ad493f4d94d38ff63d587c485aab333ea82ae4138b7148934e800a466bdb6947add22c4d6be708",
          "sha256": "00753c16b13b9faf23f52840b34d4c01b6c0ed86c864f20166d2cce860b5aeca",
          "sha1": "f90338f53a68101d3a742069db976531f646b400",
          "md5": "394a4eb8de20bab37cdab3577532185a"
        }
      ]
    }
  ]
}
