{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor/409.13.0-SNAPSHOT/resource-exec-tor-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-exec-tor",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-iosX64Main-409.13.0-SNAPSHOT.klib",
          "url": "resource-exec-tor-iosx64-409.13.0-SNAPSHOT.klib",
          "size": 10972,
          "sha512": "7b72628bc8cb2c68b1e5efad2d77d0c04bf814113e4b36bce207559c35b2dc3315c8e4e0a3c5a36566718b29f7986d625a50cf681c62d65bb345e9c6bff92a3b",
          "sha256": "5c574d38ec6c0ccecbb7132761a332c686e0bc868cdbe3d3ebc4684e9603dedd",
          "sha1": "e11e045cebd83802b95f13d456e3e8b2e845e22e",
          "md5": "77a3aae8902ebcc27c0a95ed4d881672"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-exec-tor-iosx64-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-exec-tor-iosx64-409.13.0-SNAPSHOT-sources.jar",
          "size": 6583,
          "sha512": "c672902ffe5b9f28d8e76f0dfd9dd4fe8d2a381f660a30347ead749c5fc23472992292a87a63b9ad0732bc2aa39f1c1692b08a0979843af2db2ada52d6030612",
          "sha256": "af3de202fcd1cef7fd760a62b7de77835b0cddba5b9713bb11f501092155debc",
          "sha1": "0ab8e635b48456d64de623d6a8206730e958cab9",
          "md5": "41d5ad4e86dfb2a4f930f092d1325c02"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-iosx64-409.13.0-SNAPSHOT-metadata.jar",
          "url": "resource-exec-tor-iosx64-409.13.0-SNAPSHOT-metadata.jar",
          "size": 6743,
          "sha512": "b849b4076507857856777ee00cb478439416f3d792257d13883023c9fe45664be2b343e543a68d4b9c1d726610b0586994e84ddb1d99f4e9297960367b8b50de",
          "sha256": "b5d36cbc73cbb4c8b951e676b87f5c19752f94de03cc70ad94754f3e8e49ac22",
          "sha1": "c9e5b76cf653fb208db025b689d6635604040203",
          "md5": "3dcacd0414c49adef333e353fc17c0c8"
        }
      ]
    }
  ]
}
