{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-android-unit-test-tor-gpl/409.12.0-SNAPSHOT/resource-android-unit-test-tor-gpl-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-android-unit-test-tor-gpl",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-android-unit-test-tor-gpl-release.aar",
          "url": "resource-android-unit-test-tor-gpl-android-409.12.0-SNAPSHOT.aar",
          "size": 62562966,
          "sha512": "fc62f47f513faa529f7a29c3721b86a2556cf26c6a73adfcd8b81ccda13fbf0ece06b77ee21289e4f6ce7863d9195dda53efaa6cf04dd1c3179ec493da1e4527",
          "sha256": "86758a358f4403b3dd89eb0b4164c017c4fd914e5fd83bd559f9f2af839c9d72",
          "sha1": "a0b7d0b71e24ebb8f7c2b68598e16f2a344f7be0",
          "md5": "427e9ff2ac8b6866d8f68b9b867eb847"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-android-unit-test-tor-gpl-release.aar",
          "url": "resource-android-unit-test-tor-gpl-android-409.12.0-SNAPSHOT.aar",
          "size": 62562966,
          "sha512": "fc62f47f513faa529f7a29c3721b86a2556cf26c6a73adfcd8b81ccda13fbf0ece06b77ee21289e4f6ce7863d9195dda53efaa6cf04dd1c3179ec493da1e4527",
          "sha256": "86758a358f4403b3dd89eb0b4164c017c4fd914e5fd83bd559f9f2af839c9d72",
          "sha1": "a0b7d0b71e24ebb8f7c2b68598e16f2a344f7be0",
          "md5": "427e9ff2ac8b6866d8f68b9b867eb847"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-android-unit-test-tor-gpl-android-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-android-unit-test-tor-gpl-android-409.12.0-SNAPSHOT-sources.jar",
          "size": 2635,
          "sha512": "a1ee7f658f0314d0c2f5eac5fe77278e617f7ba233f888316a7843254b0e66eee171e68b4c426657a1c9dd3a5d8fb1d6c945811285af35ebb8a7fe4197533ee7",
          "sha256": "49113d5c3ae39ba080c49a8b6a0cb8bf0dfb9f6cb10df6d95892b83a1b380750",
          "sha1": "b0362b4dcbaa0b6dd486d1bc571586572e0a6569",
          "md5": "a01342f64298435e56d85bfea1f43da5"
        }
      ]
    }
  ]
}
