{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-android-unit-test-tor-gpl/409.12.0-SNAPSHOT/resource-android-unit-test-tor-gpl-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-android-unit-test-tor-gpl",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-android-unit-test-tor-gpl-release.aar",
          "url": "resource-android-unit-test-tor-gpl-android-409.12.0-SNAPSHOT.aar",
          "size": 62712296,
          "sha512": "d64882b73e0a8789f15f13e839a6faffecce7dd12abaf3410cc04acdbc12c99218d50b5b2a9a318b367338830afe7330bc39e93baa6dcbbb4be5d0a779fef144",
          "sha256": "bc2210650c2370213d9bee662200fc68b1333935f026eff17e7d68e88778eeb2",
          "sha1": "c1edc79c198229e49c32098b7b9441993d963b30",
          "md5": "9b69fc8db89bedff3766a8011ab5c5d8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-android-unit-test-tor-gpl-release.aar",
          "url": "resource-android-unit-test-tor-gpl-android-409.12.0-SNAPSHOT.aar",
          "size": 62712296,
          "sha512": "d64882b73e0a8789f15f13e839a6faffecce7dd12abaf3410cc04acdbc12c99218d50b5b2a9a318b367338830afe7330bc39e93baa6dcbbb4be5d0a779fef144",
          "sha256": "bc2210650c2370213d9bee662200fc68b1333935f026eff17e7d68e88778eeb2",
          "sha1": "c1edc79c198229e49c32098b7b9441993d963b30",
          "md5": "9b69fc8db89bedff3766a8011ab5c5d8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-android-unit-test-tor-gpl-android-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-android-unit-test-tor-gpl-android-409.12.0-SNAPSHOT-sources.jar",
          "size": 2635,
          "sha512": "a1ee7f658f0314d0c2f5eac5fe77278e617f7ba233f888316a7843254b0e66eee171e68b4c426657a1c9dd3a5d8fb1d6c945811285af35ebb8a7fe4197533ee7",
          "sha256": "49113d5c3ae39ba080c49a8b6a0cb8bf0dfb9f6cb10df6d95892b83a1b380750",
          "sha1": "b0362b4dcbaa0b6dd486d1bc571586572e0a6569",
          "md5": "a01342f64298435e56d85bfea1f43da5"
        }
      ]
    }
  ]
}
