{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-noexec-tor/409.13.0-SNAPSHOT/resource-noexec-tor-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-noexec-tor",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-androidNativeX86Main-409.13.0-SNAPSHOT.klib",
          "url": "resource-noexec-tor-androidnativex86-409.13.0-SNAPSHOT.klib",
          "size": 38852,
          "sha512": "fa40e6a907b4de37d64f2f339614b197d8c2a442644386ea776e99099925a09ae09f6aec870b9852bf5f5f09e7cf5e2e05b7df4103ab4a37f99704406bad3db2",
          "sha256": "35888cf46b7b513d78f623df383cb900ec002a02df20c88a63beb4d79f1db737",
          "sha1": "4040bc53fb9f1b62ac0bc04d8f9d1a8cd8860a42",
          "md5": "1cd4649698d9dfdb23b5e47760b0938a"
        },
        {
          "name": "resource-noexec-tor-androidNativeX86Cinterop-kmp_torMain-409.13.0-SNAPSHOT.klib",
          "url": "resource-noexec-tor-androidnativex86-409.13.0-SNAPSHOT-cinterop-kmp_tor.klib",
          "size": 10694,
          "sha512": "28c3f2e9773ccbdea7300fec2617056585f906211ba474cb0622a63fdd665aa63886a193f9c4fd93114cd5174902871454b1952d0b566318600485be1bac1fa5",
          "sha256": "c8b92c6da2fe9027e60699af894eae202e601486e426878b381fc0b299932338",
          "sha1": "6f9db76bb126f094d2d6e29f120605f56935b059",
          "md5": "e300fb4095e82aec66f33b45af66a9b2"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-noexec-tor-androidnativex86-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-noexec-tor-androidnativex86-409.13.0-SNAPSHOT-sources.jar",
          "size": 17943,
          "sha512": "3d9a2268373d438c85a1c390b717ee373ba725c96f04b9ecde0fe7da13cdadc1b6bae321b8c2c23e9ca915b7be60dd0ece6def83a1548a3c3a9f2d3878ced672",
          "sha256": "13dbc89eedba1e9bbf68293d732d428c835f62cd47691f4b033eec7885a8d319",
          "sha1": "6c5742af4d5c4226c875f2734135a5049454f21c",
          "md5": "37bcd6b4c4972a89a3c0566134788604"
        }
      ]
    }
  ]
}
