{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-noexec-tor-gpl/409.12.0-SNAPSHOT/resource-noexec-tor-gpl-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-noexec-tor-gpl",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-gpl-jvm-409.12.0-SNAPSHOT.jar",
          "url": "resource-noexec-tor-gpl-jvm-409.12.0-SNAPSHOT.jar",
          "size": 220295,
          "sha512": "f0bd6e11eb3673dbc0737a2f61a63dd8925dd5a84e5a5e0716a9728df5faa654265dbb576b99db2f46fe9e8d670c7a76d869fa8a17e9eacfa5df7348c69808cd",
          "sha256": "dd1ab5b77ae57c0d6f01f22ddac9df0e1a97d3745bf1703a15b8cb94ca0ff820",
          "sha1": "c8cebb19d78d1ac0e84622afb761018dca7d0a29",
          "md5": "c12319ed9d35db66e5e9ae68d4aa8dbe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-lib-tor-gpl",
          "version": {
            "requires": "409.12.0-SNAPSHOT"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-gpl-jvm-409.12.0-SNAPSHOT.jar",
          "url": "resource-noexec-tor-gpl-jvm-409.12.0-SNAPSHOT.jar",
          "size": 220295,
          "sha512": "f0bd6e11eb3673dbc0737a2f61a63dd8925dd5a84e5a5e0716a9728df5faa654265dbb576b99db2f46fe9e8d670c7a76d869fa8a17e9eacfa5df7348c69808cd",
          "sha256": "dd1ab5b77ae57c0d6f01f22ddac9df0e1a97d3745bf1703a15b8cb94ca0ff820",
          "sha1": "c8cebb19d78d1ac0e84622afb761018dca7d0a29",
          "md5": "c12319ed9d35db66e5e9ae68d4aa8dbe"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "resource-noexec-tor-gpl-jvm-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-noexec-tor-gpl-jvm-409.12.0-SNAPSHOT-sources.jar",
          "size": 16079,
          "sha512": "8e1a4272f0ac4f36151ef9845ff6af6193eeb4fe9d19aed414cf8d8e5fc74f798ab8af0fd9799030ae3032af03014c7f1bec68c299656afa6f96b694fc6f4c00",
          "sha256": "f423691ca5669067c376262f1dd56bf5b576bef88f3d84b20526347e4e825e6c",
          "sha1": "392a988d76375a1bcb9decbc99922b8b95f009de",
          "md5": "d6538bbd34cb0d58004fedc3cf1e6cc0"
        }
      ]
    }
  ]
}
