{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-lib-tor/409.13.0/resource-lib-tor-409.13.0.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-lib-tor",
    "version": "409.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-iosX64Main-409.13.0.klib",
          "url": "resource-lib-tor-iosx64-409.13.0.klib",
          "size": 6838981,
          "sha512": "17650d37feb83475f1c7d3c4be3bd423a2d5086574bae03be5b9602b41a2265259c8045164b505fa17cd6c84d489eea607fc69bd715ad5057353c4bcce8f1126",
          "sha256": "d5b943aff6a67466b3dbbed40574f4cbacefa426abaffebb41f3a61077690215",
          "sha1": "429f42fd7cec99a6dc961f73e47474a39d32362c",
          "md5": "8fe8d0ee6091225c0233076d65734c1c"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-lib-tor-iosx64-409.13.0-sources.jar",
          "url": "resource-lib-tor-iosx64-409.13.0-sources.jar",
          "size": 3286082,
          "sha512": "bc23b50628fad187565bd731287604c678440be029a53401f7044f4fc18068a21aba3bfa15468b0e86fe4c639a10a3f48b1d416273d46a0c8ac1101d9e110d35",
          "sha256": "73a348d4bbd38e2eac617f8c1959230a85646e214cb72fc390cfdafba623c4a8",
          "sha1": "f003af09ec1b16a7e84064428aca342c6c7cce11",
          "md5": "0e5ade356563fe13b092ec8e0a76d053"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-iosx64-409.13.0-metadata.jar",
          "url": "resource-lib-tor-iosx64-409.13.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
