{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor-gpl/409.13.0-rc1/resource-exec-tor-gpl-409.13.0-rc1.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-exec-tor-gpl",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-androidNativeX64Main-409.13.0-rc1.klib",
          "url": "resource-exec-tor-gpl-androidnativex64-409.13.0-rc1.klib",
          "size": 23801,
          "sha512": "37a41d67cbdaa441ff021541e8a9178bc78d0f798436701419c5ab5b3ade8103bf4b597c388a020db0dc96eda9a0fc1bff5f8fb3066373591924ee5650ea2ac2",
          "sha256": "d9ebaa60cf5ef06f45bef857238a15627d4a55e94b1bd006772477f470cb2392",
          "sha1": "1eb68ced89fe39f0eac5b40706d19a8892fc38b8",
          "md5": "662f8c78cd07c9e9d8499983bc896e8e"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-exec-tor-gpl-androidnativex64-409.13.0-rc1-sources.jar",
          "url": "resource-exec-tor-gpl-androidnativex64-409.13.0-rc1-sources.jar",
          "size": 11711,
          "sha512": "cbc9c98a2eec49e576023f221a4c64d2f8c41624fcb727e3821163f3e5da98ec60b90ad2227c2e99798e7795ebf4859c35c3009463b1d4e97d3f7f08535af115",
          "sha256": "be928b9f248c958477cc8bc557a5c91a7da67ad01280376547e693aef6708a38",
          "sha1": "d06d3b8f277c27c1fb3689e5dc0e2f3cbc68893c",
          "md5": "f87f6530ffcc3e90e4e2a856c1ceb3cd"
        }
      ]
    }
  ]
}
