{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-compilation-lib-tor/409.13.0-rc1/resource-compilation-lib-tor-409.13.0-rc1.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-compilation-lib-tor",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-compilation-lib-tor-release.aar",
          "url": "resource-compilation-lib-tor-android-409.13.0-rc1.aar",
          "size": 14730529,
          "sha512": "d9146c2f10805a6c0b7299753d72500f14262b42bdc810b4515c2931e8dac5d2d4f97fc4170687bea9b37c04bf66330e207bbd721423b58f420e95ae2087ab3a",
          "sha256": "bfa735e103fca35f2ce2351b9e95fa6b127e3b26ebf5a20c209a9e32920035e0",
          "sha1": "a8c4fa1be4fdb8bde03a7490eb9105943c59495b",
          "md5": "1db442f5167b30fb1c292501bb609cf5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-compilation-lib-tor-release.aar",
          "url": "resource-compilation-lib-tor-android-409.13.0-rc1.aar",
          "size": 14730529,
          "sha512": "d9146c2f10805a6c0b7299753d72500f14262b42bdc810b4515c2931e8dac5d2d4f97fc4170687bea9b37c04bf66330e207bbd721423b58f420e95ae2087ab3a",
          "sha256": "bfa735e103fca35f2ce2351b9e95fa6b127e3b26ebf5a20c209a9e32920035e0",
          "sha1": "a8c4fa1be4fdb8bde03a7490eb9105943c59495b",
          "md5": "1db442f5167b30fb1c292501bb609cf5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-compilation-lib-tor-android-409.13.0-rc1-sources.jar",
          "url": "resource-compilation-lib-tor-android-409.13.0-rc1-sources.jar",
          "size": 4033,
          "sha512": "ab98f035bebbfece927f889039fa5562cc31284547a722630244ba66f0133e8a6bbf184130ce616afd6ed3c71921e34658060cb3acad419f763d8319c5a3fb48",
          "sha256": "84ed2d37f9acd2fb20d8569eb4eaf3efdec16833ec0949ec54a37b9972097d0b",
          "sha1": "2afd79f162572ddfecb3d63627bab20f41ba3d3e",
          "md5": "b30d4ff64bd0b7b7fc7ac149264458e1"
        }
      ]
    }
  ]
}
