{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-geoip/409.12.0-SNAPSHOT/resource-geoip-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-geoip",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-geoip-androidNativeArm64Main-409.12.0-SNAPSHOT.klib",
          "url": "resource-geoip-androidnativearm64-409.12.0-SNAPSHOT.klib",
          "size": 9560433,
          "sha512": "df816fd75dda0113e33cc8f9ec06be3fe26eec0127ba551e795d335b0f23da1876550a1d9c50c33bea48e231e899d69eeb817ad55fa2fff84bd2188cd0fb01b6",
          "sha256": "ff22a7a708e72038204939518fe6b5591927376671f5702abdeb2ed2a370b64f",
          "sha1": "4c9fffbbc5203aec0bc6cf3df0eea36d77f5ec4c",
          "md5": "49f4580d97a8267f2414f763424beeef"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-geoip-androidnativearm64-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-geoip-androidnativearm64-409.12.0-SNAPSHOT-sources.jar",
          "size": 4581362,
          "sha512": "d41ca04f478f47bb5420516873969136141cf3cffe76919c28ad493f4d94d38ff63d587c485aab333ea82ae4138b7148934e800a466bdb6947add22c4d6be708",
          "sha256": "00753c16b13b9faf23f52840b34d4c01b6c0ed86c864f20166d2cce860b5aeca",
          "sha1": "f90338f53a68101d3a742069db976531f646b400",
          "md5": "394a4eb8de20bab37cdab3577532185a"
        }
      ]
    }
  ]
}
