{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor-gpl/409.13.0-SNAPSHOT/resource-exec-tor-gpl-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-exec-tor-gpl",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-iosSimulatorArm64Main-409.13.0-SNAPSHOT.klib",
          "url": "resource-exec-tor-gpl-iossimulatorarm64-409.13.0-SNAPSHOT.klib",
          "size": 11061,
          "sha512": "2154bc47d24dc816ee0b24144f151e4dd17fb493abc58401b025be43ec93028c190f8a2089c29a6dad7ebc896d5b7083a9ff247a6e5439a21fb64485dfbfde14",
          "sha256": "83d7954f28f0112a741688b3526bf49114bc7a8763968e3091cb08d08f2a6ddc",
          "sha1": "51face10b6782ab8683aa7eb2d34900e688af228",
          "md5": "86a153fcabea919a1372c9f6cf0ef6e3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-exec-tor-gpl-iossimulatorarm64-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-exec-tor-gpl-iossimulatorarm64-409.13.0-SNAPSHOT-sources.jar",
          "size": 6583,
          "sha512": "c672902ffe5b9f28d8e76f0dfd9dd4fe8d2a381f660a30347ead749c5fc23472992292a87a63b9ad0732bc2aa39f1c1692b08a0979843af2db2ada52d6030612",
          "sha256": "af3de202fcd1cef7fd760a62b7de77835b0cddba5b9713bb11f501092155debc",
          "sha1": "0ab8e635b48456d64de623d6a8206730e958cab9",
          "md5": "41d5ad4e86dfb2a4f930f092d1325c02"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-iossimulatorarm64-409.13.0-SNAPSHOT-metadata.jar",
          "url": "resource-exec-tor-gpl-iossimulatorarm64-409.13.0-SNAPSHOT-metadata.jar",
          "size": 6750,
          "sha512": "2ea8de171b13b4ea3b22cda8ca57e388c81881726b24d69fdd2987fd4328a9975fb8dd7d8ca1bd8a4eb3da61f343d4c246134608a05ba6643763b40b01e602dd",
          "sha256": "ab0e24e9b2d129b0a1fadd81eeb8c62ffcd0da6ed2bc4624e6f0c137a8ed640f",
          "sha1": "5bc8b9a14ee730194ab13be424c939028b7d5667",
          "md5": "5e37fef943be89220564a45802655da3"
        }
      ]
    }
  ]
}
