{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor/409.12.0-SNAPSHOT/resource-exec-tor-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-exec-tor",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-androidNativeX64Main-409.12.0-SNAPSHOT.klib",
          "url": "resource-exec-tor-androidnativex64-409.12.0-SNAPSHOT.klib",
          "size": 23788,
          "sha512": "7e24c55818d82ef32c194b06a76937e0ce5ea86ba3b5836d1292765bdd9892ef15aa26b10b0c52ec705fdd9a3635fdcc85abfc4df6c350a82b71de4b52b370da",
          "sha256": "b969dda12a2190064c7ceaa92f727c3a544d3495bddf465d374caba035b6a6b4",
          "sha1": "6e8653fffff04d53ca4b8323100e7d632d20a2d5",
          "md5": "f1d2dc4b91a5b93dfd11ec55970baf6b"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-exec-tor-androidnativex64-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-exec-tor-androidnativex64-409.12.0-SNAPSHOT-sources.jar",
          "size": 11711,
          "sha512": "cbc9c98a2eec49e576023f221a4c64d2f8c41624fcb727e3821163f3e5da98ec60b90ad2227c2e99798e7795ebf4859c35c3009463b1d4e97d3f7f08535af115",
          "sha256": "be928b9f248c958477cc8bc557a5c91a7da67ad01280376547e693aef6708a38",
          "sha1": "d06d3b8f277c27c1fb3689e5dc0e2f3cbc68893c",
          "md5": "f87f6530ffcc3e90e4e2a856c1ceb3cd"
        }
      ]
    }
  ]
}
