{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-noexec-tor/409.12.0-SNAPSHOT/resource-noexec-tor-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-noexec-tor",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-jvm-409.12.0-SNAPSHOT.jar",
          "url": "resource-noexec-tor-jvm-409.12.0-SNAPSHOT.jar",
          "size": 220241,
          "sha512": "6006c91078e781cd8517819f6ce90856ef1765e430e31d42ed13c1c5253711045c093f6072136ab2f014d134ed6f3e14e7d39908ceae400258dacc93e9a2e8cf",
          "sha256": "4e7dc86088568e91254c50cdeedc915eff16391ba7935e9f3e909132351e24df",
          "sha1": "d4d3d5f31aabc71e6e147b988da2eca0c99bd426",
          "md5": "c72ae1e8251ca846c3bd71ff9b38ee73"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-lib-tor",
          "version": {
            "requires": "409.12.0-SNAPSHOT"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-jvm-409.12.0-SNAPSHOT.jar",
          "url": "resource-noexec-tor-jvm-409.12.0-SNAPSHOT.jar",
          "size": 220241,
          "sha512": "6006c91078e781cd8517819f6ce90856ef1765e430e31d42ed13c1c5253711045c093f6072136ab2f014d134ed6f3e14e7d39908ceae400258dacc93e9a2e8cf",
          "sha256": "4e7dc86088568e91254c50cdeedc915eff16391ba7935e9f3e909132351e24df",
          "sha1": "d4d3d5f31aabc71e6e147b988da2eca0c99bd426",
          "md5": "c72ae1e8251ca846c3bd71ff9b38ee73"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "resource-noexec-tor-jvm-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-noexec-tor-jvm-409.12.0-SNAPSHOT-sources.jar",
          "size": 16079,
          "sha512": "8e1a4272f0ac4f36151ef9845ff6af6193eeb4fe9d19aed414cf8d8e5fc74f798ab8af0fd9799030ae3032af03014c7f1bec68c299656afa6f96b694fc6f4c00",
          "sha256": "f423691ca5669067c376262f1dd56bf5b576bef88f3d84b20526347e4e825e6c",
          "sha1": "392a988d76375a1bcb9decbc99922b8b95f009de",
          "md5": "d6538bbd34cb0d58004fedc3cf1e6cc0"
        }
      ]
    }
  ]
}
