{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-noexec-tor-gpl/409.13.0-rc1/resource-noexec-tor-gpl-409.13.0-rc1.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-noexec-tor-gpl",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-gpl-androidNativeX86Main-409.13.0-rc1.klib",
          "url": "resource-noexec-tor-gpl-androidnativex86-409.13.0-rc1.klib",
          "size": 38862,
          "sha512": "455b0d4a0aac49b3fea1fd359772fa337cba67669bf5a28dc851b3b81b98cc6d17da98ee810a1dc37bb3719f78373c49d71e744855eb1a62497d39c4caaf53cf",
          "sha256": "f5ab1468363f68a1275d00166a0575bf34d77fa50f14983dfbbab151b46d20bb",
          "sha1": "2720c89b1eea4fc7c3ac0b2e5e08bc418eda53b5",
          "md5": "babb3100fda15f3d2c14aa73191ffa66"
        },
        {
          "name": "resource-noexec-tor-gpl-androidNativeX86Cinterop-kmp_torMain-409.13.0-rc1.klib",
          "url": "resource-noexec-tor-gpl-androidnativex86-409.13.0-rc1-cinterop-kmp_tor.klib",
          "size": 10706,
          "sha512": "65f77834bb5b5210af653523499a48bf2db2451d91154279f9ff45413642de2adc3563527bbf20f73c81c38c55e80bf1944a1c29d88bf7c4c4c4971a62ed622a",
          "sha256": "de3f1a9d37ec3ba76bee8398be3fe8bae6e3f1ec7ef6132524fd41c2e80da9c7",
          "sha1": "28bc4222678b3988a809ac7a9b100d9e2ab4df06",
          "md5": "427b6b5e419031f823087667600b8859"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-noexec-tor-gpl-androidnativex86-409.13.0-rc1-sources.jar",
          "url": "resource-noexec-tor-gpl-androidnativex86-409.13.0-rc1-sources.jar",
          "size": 17943,
          "sha512": "3d9a2268373d438c85a1c390b717ee373ba725c96f04b9ecde0fe7da13cdadc1b6bae321b8c2c23e9ca915b7be60dd0ece6def83a1548a3c3a9f2d3878ced672",
          "sha256": "13dbc89eedba1e9bbf68293d732d428c835f62cd47691f4b033eec7885a8d319",
          "sha1": "6c5742af4d5c4226c875f2734135a5049454f21c",
          "md5": "37bcd6b4c4972a89a3c0566134788604"
        }
      ]
    }
  ]
}
