{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-compilation-exec-tor-gpl/409.12.0-SNAPSHOT/resource-compilation-exec-tor-gpl-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-compilation-exec-tor-gpl",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-compilation-exec-tor-gpl-release.aar",
          "url": "resource-compilation-exec-tor-gpl-android-409.12.0-SNAPSHOT.aar",
          "size": 9661,
          "sha512": "18d8430db72614e933b8a9866a0a04ed934b6a527705372bc1656c6afcdc2c41a183fe4f97df8bc093b52820a28609f0344245a3c4d001982e9852d4288de33b",
          "sha256": "7fd1e0525bf930e7f54a407911ff0bbb3f990cc6849993fda8eee06beabc6277",
          "sha1": "7457dcc18e1edcf30f6bd618d0af7add917e2520",
          "md5": "70a76e7f3ca86ef0995bb2ce89466ac2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-compilation-lib-tor-gpl",
          "version": {
            "requires": "409.12.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-compilation-exec-tor-gpl-release.aar",
          "url": "resource-compilation-exec-tor-gpl-android-409.12.0-SNAPSHOT.aar",
          "size": 9661,
          "sha512": "18d8430db72614e933b8a9866a0a04ed934b6a527705372bc1656c6afcdc2c41a183fe4f97df8bc093b52820a28609f0344245a3c4d001982e9852d4288de33b",
          "sha256": "7fd1e0525bf930e7f54a407911ff0bbb3f990cc6849993fda8eee06beabc6277",
          "sha1": "7457dcc18e1edcf30f6bd618d0af7add917e2520",
          "md5": "70a76e7f3ca86ef0995bb2ce89466ac2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-compilation-exec-tor-gpl-android-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-compilation-exec-tor-gpl-android-409.12.0-SNAPSHOT-sources.jar",
          "size": 3213,
          "sha512": "9db7483b258b403f36821fc9f22a1607e91394f37ff82eca6e1993ba87e0252529ac399f252ee5c2c13c7ea0cc60b12f59029c30b4f142f38b2817e087a76cbe",
          "sha256": "5614b2c29b287cbdfcb62c19eb5aadf523154ed01dd85cfd0724938172e8060a",
          "sha1": "ce7e37fa23fc6d6a8d142894a9c442832b720158",
          "md5": "9017018508a71ad2ff0dd848ebb2beee"
        }
      ]
    }
  ]
}
