{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor-gpl/409.13.0-rc1/resource-exec-tor-gpl-409.13.0-rc1.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-exec-tor-gpl",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-iosSimulatorArm64Main-409.13.0-rc1.klib",
          "url": "resource-exec-tor-gpl-iossimulatorarm64-409.13.0-rc1.klib",
          "size": 11071,
          "sha512": "e0a3e9c6cfdfd0cbe4ac17fac6d89aa6e5d5bfdc9f771d2b1dc437e60122c08fde4230e960ee1b0249a5704ba3755827e827b5848724e69dc315a0323293e927",
          "sha256": "dbc0d2486016fea0c2124eda23246f94caa967aeeecb5018f79071bec71252e6",
          "sha1": "37ff9dbddc8f0158293eccc6691729abaa07798e",
          "md5": "4065b960a371557974ef3cf6fb27f764"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-exec-tor-gpl-iossimulatorarm64-409.13.0-rc1-sources.jar",
          "url": "resource-exec-tor-gpl-iossimulatorarm64-409.13.0-rc1-sources.jar",
          "size": 6583,
          "sha512": "c672902ffe5b9f28d8e76f0dfd9dd4fe8d2a381f660a30347ead749c5fc23472992292a87a63b9ad0732bc2aa39f1c1692b08a0979843af2db2ada52d6030612",
          "sha256": "af3de202fcd1cef7fd760a62b7de77835b0cddba5b9713bb11f501092155debc",
          "sha1": "0ab8e635b48456d64de623d6a8206730e958cab9",
          "md5": "41d5ad4e86dfb2a4f930f092d1325c02"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-iossimulatorarm64-409.13.0-rc1-metadata.jar",
          "url": "resource-exec-tor-gpl-iossimulatorarm64-409.13.0-rc1-metadata.jar",
          "size": 6755,
          "sha512": "496bf7065f3de02afd7ccacfd2674a77de455f8a04aff43c96f502c1328a408e3104df7ca8ca628984f3e05d598e5760262e9dc84a30ed3b54bc76ae0f5d58c1",
          "sha256": "3a80eccfe83a21522d44bbb9df5bda518b036cc219b7cc458a3f6585d2d9a9a3",
          "sha1": "f427537d6e2e77e9b120095493cb8de2f28c3a6b",
          "md5": "bee141be3a1c35977699c6567c615896"
        }
      ]
    }
  ]
}
