{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-noexec-tor/409.13.0-SNAPSHOT/resource-noexec-tor-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-noexec-tor",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-release.aar",
          "url": "resource-noexec-tor-android-409.13.0-SNAPSHOT.aar",
          "size": 53921,
          "sha512": "47af7c18a04a1d31946961d6231bd73519d401713063c2bcf05c53f32f26d9c1429070a66e025d523db1d49c38e6511cfed883d77b9950352788de94e30ce929",
          "sha256": "18627b6f0d500935d10be84cb5f64ffd8151357671dfc51103fc9c1bad822602",
          "sha1": "ede43e5eb4e4f080f4d2b78cfb1a4882cf61b155",
          "md5": "0ba52a9764e002298137388d0004c59e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-lib-tor",
          "version": {
            "requires": "409.13.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-release.aar",
          "url": "resource-noexec-tor-android-409.13.0-SNAPSHOT.aar",
          "size": 53921,
          "sha512": "47af7c18a04a1d31946961d6231bd73519d401713063c2bcf05c53f32f26d9c1429070a66e025d523db1d49c38e6511cfed883d77b9950352788de94e30ce929",
          "sha256": "18627b6f0d500935d10be84cb5f64ffd8151357671dfc51103fc9c1bad822602",
          "sha1": "ede43e5eb4e4f080f4d2b78cfb1a4882cf61b155",
          "md5": "0ba52a9764e002298137388d0004c59e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-noexec-tor-android-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-noexec-tor-android-409.13.0-SNAPSHOT-sources.jar",
          "size": 17291,
          "sha512": "0d2d40b1cce34e1aa72e6c08cd205f9cb52d48cf6bb9b766349794979b1f786ace22ae2b02a1bab5d43d28fba638dca2b34997512d8b83fbff66d26b39b254f6",
          "sha256": "0c5367cd4f29c0257e07adca0fe13dbe1f4494c032ae2a0790c9bef12bd07c25",
          "sha1": "21394573ca9475ca430d6ef4a5da5c2978a02523",
          "md5": "0ee764f4d73e5c57b740ffddf72fcb23"
        }
      ]
    }
  ]
}
