{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-lib-tor/409.13.0-rc1/resource-lib-tor-409.13.0-rc1.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-lib-tor",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-release.aar",
          "url": "resource-lib-tor-android-409.13.0-rc1.aar",
          "size": 28092,
          "sha512": "5ebf5172472ccb1f09d036decbf7933985e09ddf58206a990b4bc7edc9ee3cf36280a21a796e532ed220d61ae869837b6fff786a2d97c62c90b6e5c1330d7af6",
          "sha256": "31a9481730a8774e529381d18d908894f941f38d6a72cfb32d15fb8bf7759576",
          "sha1": "dda7c83840bd5d5dd4cde98eae882174df7ff8e4",
          "md5": "0b48892a9058292e014b88d0dc178f8e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-compilation-lib-tor",
          "version": {
            "requires": "409.13.0-rc1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-release.aar",
          "url": "resource-lib-tor-android-409.13.0-rc1.aar",
          "size": 28092,
          "sha512": "5ebf5172472ccb1f09d036decbf7933985e09ddf58206a990b4bc7edc9ee3cf36280a21a796e532ed220d61ae869837b6fff786a2d97c62c90b6e5c1330d7af6",
          "sha256": "31a9481730a8774e529381d18d908894f941f38d6a72cfb32d15fb8bf7759576",
          "sha1": "dda7c83840bd5d5dd4cde98eae882174df7ff8e4",
          "md5": "0b48892a9058292e014b88d0dc178f8e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-lib-tor-android-409.13.0-rc1-sources.jar",
          "url": "resource-lib-tor-android-409.13.0-rc1-sources.jar",
          "size": 7975,
          "sha512": "d3980939ae440cf541fd02c3162c9b907870bf68cb4eba04310ed9b17501823fd4827b2b1ae0f63ab4e822b0646d34d35e91b6160311f46cf1e63241438c3c41",
          "sha256": "04025880db2e41fa501c6f9478dadc317342f271bbd3ce0bd74c906a53742610",
          "sha1": "ea9ff99fbeff9d04aa9c1705da1818278f70deac",
          "md5": "f7cfa90b447239cd0e3dc4618f3d4f53"
        }
      ]
    }
  ]
}
