{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor-gpl/409.13.0-rc1/resource-exec-tor-gpl-409.13.0-rc1.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-exec-tor-gpl",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-iosX64Main-409.13.0-rc1.klib",
          "url": "resource-exec-tor-gpl-iosx64-409.13.0-rc1.klib",
          "size": 10988,
          "sha512": "32fce5a6128214065f21bd54f6ef90670fffcc4e7c437625c5510aad6f6843264366e99c58923bb2a4a99277a2388cd721a2fc58989e9a2d1a7075fae6d6797d",
          "sha256": "6d25eadec570198f3bab96918bce6be4833337060e35bce50515dc047b326c0d",
          "sha1": "b0bd93b0ca4d682f33b3ab7aec119423a7547de6",
          "md5": "ef120b10de3b72002f552949ce643a9f"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-exec-tor-gpl-iosx64-409.13.0-rc1-sources.jar",
          "url": "resource-exec-tor-gpl-iosx64-409.13.0-rc1-sources.jar",
          "size": 6583,
          "sha512": "c672902ffe5b9f28d8e76f0dfd9dd4fe8d2a381f660a30347ead749c5fc23472992292a87a63b9ad0732bc2aa39f1c1692b08a0979843af2db2ada52d6030612",
          "sha256": "af3de202fcd1cef7fd760a62b7de77835b0cddba5b9713bb11f501092155debc",
          "sha1": "0ab8e635b48456d64de623d6a8206730e958cab9",
          "md5": "41d5ad4e86dfb2a4f930f092d1325c02"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-iosx64-409.13.0-rc1-metadata.jar",
          "url": "resource-exec-tor-gpl-iosx64-409.13.0-rc1-metadata.jar",
          "size": 6755,
          "sha512": "496bf7065f3de02afd7ccacfd2674a77de455f8a04aff43c96f502c1328a408e3104df7ca8ca628984f3e05d598e5760262e9dc84a30ed3b54bc76ae0f5d58c1",
          "sha256": "3a80eccfe83a21522d44bbb9df5bda518b036cc219b7cc458a3f6585d2d9a9a3",
          "sha1": "f427537d6e2e77e9b120095493cb8de2f28c3a6b",
          "md5": "bee141be3a1c35977699c6567c615896"
        }
      ]
    }
  ]
}
