{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-exec-tor-gpl",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-metadata-409.13.0-rc1.jar",
          "url": "resource-exec-tor-gpl-409.13.0-rc1.jar",
          "size": 19584,
          "sha512": "148559c92ac68d6ffc61987af1ac796a7890e334fbffc87d3994ae7e9eb7f699c4e638aa66be99c1e797b4db8556b1198b13660cfbe54a7a9c6bba41ef31583a",
          "sha256": "050a506ec13f0cfbb9651d13337c8b5ebf43f04d95fb0804edaef1fe07283f76",
          "sha1": "30929609bf9d23951649e086a5dad72deb90eb3f",
          "md5": "d91ba0568de39abc08366acd5f428192"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "resource-exec-tor-gpl-kotlin-409.13.0-rc1-sources.jar",
          "url": "resource-exec-tor-gpl-409.13.0-rc1-sources.jar",
          "size": 14782,
          "sha512": "a3086aa239a657461bd310738905d907cdb1ddba6abc2579d4c128e61f6a708f570d9959bdbc4c86e1f3878eef42423805c6c3e5721137c7ceba395791e50412",
          "sha256": "0c828e2ec3a88e46146cd9ff0101429795c40639698f69f0adbe1bbd8d4917f3",
          "sha1": "8b876773b48b11e0cf0a9f51855beb18d4ca21b3",
          "md5": "05862dfe622e394f48f94b2ba16de011"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-android/409.13.0-rc1/resource-exec-tor-gpl-android-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-android",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-android/409.13.0-rc1/resource-exec-tor-gpl-android-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-android",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-android/409.13.0-rc1/resource-exec-tor-gpl-android-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-android",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-androidnativearm32/409.13.0-rc1/resource-exec-tor-gpl-androidnativearm32-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-androidnativearm32",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-androidnativearm32/409.13.0-rc1/resource-exec-tor-gpl-androidnativearm32-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-androidnativearm32",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-androidnativearm64/409.13.0-rc1/resource-exec-tor-gpl-androidnativearm64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-androidnativearm64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-androidnativearm64/409.13.0-rc1/resource-exec-tor-gpl-androidnativearm64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-androidnativearm64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-androidnativex64/409.13.0-rc1/resource-exec-tor-gpl-androidnativex64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-androidnativex64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-androidnativex64/409.13.0-rc1/resource-exec-tor-gpl-androidnativex64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-androidnativex64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-androidnativex86/409.13.0-rc1/resource-exec-tor-gpl-androidnativex86-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-androidnativex86",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-androidnativex86/409.13.0-rc1/resource-exec-tor-gpl-androidnativex86-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-androidnativex86",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-iosarm64/409.13.0-rc1/resource-exec-tor-gpl-iosarm64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-iosarm64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-iosarm64/409.13.0-rc1/resource-exec-tor-gpl-iosarm64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-iosarm64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-iosarm64/409.13.0-rc1/resource-exec-tor-gpl-iosarm64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-iosarm64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-iossimulatorarm64/409.13.0-rc1/resource-exec-tor-gpl-iossimulatorarm64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-iossimulatorarm64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-iossimulatorarm64/409.13.0-rc1/resource-exec-tor-gpl-iossimulatorarm64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-iossimulatorarm64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-iossimulatorarm64/409.13.0-rc1/resource-exec-tor-gpl-iossimulatorarm64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-iossimulatorarm64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-iosx64/409.13.0-rc1/resource-exec-tor-gpl-iosx64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-iosx64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-iosx64/409.13.0-rc1/resource-exec-tor-gpl-iosx64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-iosx64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-iosx64/409.13.0-rc1/resource-exec-tor-gpl-iosx64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-iosx64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-jvm/409.13.0-rc1/resource-exec-tor-gpl-jvm-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-jvm",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-jvm/409.13.0-rc1/resource-exec-tor-gpl-jvm-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-jvm",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-exec-tor-gpl-jvm/409.13.0-rc1/resource-exec-tor-gpl-jvm-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-gpl-jvm",
        "version": "409.13.0-rc1"
      }
    }
  ]
}
