{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-android-unit-test-tor-gpl/409.13.0-SNAPSHOT/resource-android-unit-test-tor-gpl-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-android-unit-test-tor-gpl",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-android-unit-test-tor-gpl-release.aar",
          "url": "resource-android-unit-test-tor-gpl-android-409.13.0-SNAPSHOT.aar",
          "size": 62735033,
          "sha512": "9ab0deca05ceb4ed6b971b25be62e0b3ac70737001887afbf2a439acf0bc66b4e2075caf632a7ff8ab71b2fc4e80f8cfff709c9390ea71a0e07ef2ec9508c5a5",
          "sha256": "4bf6e09d4acccbc7297843e4b459822e18687d1ca510ce6df80e566cc1d791a2",
          "sha1": "22a040e3952d6f10a4af97a0f5050dc8204a169b",
          "md5": "31ad433c32d095203a76312b6035b5f9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-android-unit-test-tor-gpl-release.aar",
          "url": "resource-android-unit-test-tor-gpl-android-409.13.0-SNAPSHOT.aar",
          "size": 62735033,
          "sha512": "9ab0deca05ceb4ed6b971b25be62e0b3ac70737001887afbf2a439acf0bc66b4e2075caf632a7ff8ab71b2fc4e80f8cfff709c9390ea71a0e07ef2ec9508c5a5",
          "sha256": "4bf6e09d4acccbc7297843e4b459822e18687d1ca510ce6df80e566cc1d791a2",
          "sha1": "22a040e3952d6f10a4af97a0f5050dc8204a169b",
          "md5": "31ad433c32d095203a76312b6035b5f9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-android-unit-test-tor-gpl-android-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-android-unit-test-tor-gpl-android-409.13.0-SNAPSHOT-sources.jar",
          "size": 2635,
          "sha512": "a1ee7f658f0314d0c2f5eac5fe77278e617f7ba233f888316a7843254b0e66eee171e68b4c426657a1c9dd3a5d8fb1d6c945811285af35ebb8a7fe4197533ee7",
          "sha256": "49113d5c3ae39ba080c49a8b6a0cb8bf0dfb9f6cb10df6d95892b83a1b380750",
          "sha1": "b0362b4dcbaa0b6dd486d1bc571586572e0a6569",
          "md5": "a01342f64298435e56d85bfea1f43da5"
        }
      ]
    }
  ]
}
