{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-noexec-tor-gpl/409.13.0-SNAPSHOT/resource-noexec-tor-gpl-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-noexec-tor-gpl",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-gpl-release.aar",
          "url": "resource-noexec-tor-gpl-android-409.13.0-SNAPSHOT.aar",
          "size": 53973,
          "sha512": "edbd11d185260d60d683fd239cc0437d8a3bf1096283943fa337e7d194e6d3e30d6cbe3709c51d78c643b3d968c598ccc42a0b453a5df7e2cc503e3eba2994fd",
          "sha256": "27a591238f0fe5af4eb8a8761009ff4b6458b4330e167047bb9c1e3e6704ef7e",
          "sha1": "5a6a1833e6f3e0a5432b2789650918c6ca17586a",
          "md5": "095cf8c256c076cb97855f4a331731c1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-lib-tor-gpl",
          "version": {
            "requires": "409.13.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-noexec-tor-gpl-release.aar",
          "url": "resource-noexec-tor-gpl-android-409.13.0-SNAPSHOT.aar",
          "size": 53973,
          "sha512": "edbd11d185260d60d683fd239cc0437d8a3bf1096283943fa337e7d194e6d3e30d6cbe3709c51d78c643b3d968c598ccc42a0b453a5df7e2cc503e3eba2994fd",
          "sha256": "27a591238f0fe5af4eb8a8761009ff4b6458b4330e167047bb9c1e3e6704ef7e",
          "sha1": "5a6a1833e6f3e0a5432b2789650918c6ca17586a",
          "md5": "095cf8c256c076cb97855f4a331731c1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-noexec-tor-gpl-android-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-noexec-tor-gpl-android-409.13.0-SNAPSHOT-sources.jar",
          "size": 17291,
          "sha512": "0d2d40b1cce34e1aa72e6c08cd205f9cb52d48cf6bb9b766349794979b1f786ace22ae2b02a1bab5d43d28fba638dca2b34997512d8b83fbff66d26b39b254f6",
          "sha256": "0c5367cd4f29c0257e07adca0fe13dbe1f4494c032ae2a0790c9bef12bd07c25",
          "sha1": "21394573ca9475ca430d6ef4a5da5c2978a02523",
          "md5": "0ee764f4d73e5c57b740ffddf72fcb23"
        }
      ]
    }
  ]
}
