{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-lib-tor-gpl/409.13.0-SNAPSHOT/resource-lib-tor-gpl-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-lib-tor-gpl",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-gpl-release.aar",
          "url": "resource-lib-tor-gpl-android-409.13.0-SNAPSHOT.aar",
          "size": 28101,
          "sha512": "80bf00a48c3a776b54af83f19fa75365fa13f296a0ae495c973a3e71906c2f41e812d2c3c3d41c86f1b13fba08eef72d7e7ada312712e4f68aafcfac6360d3cd",
          "sha256": "3596fa41cbc57b86956e6d003dccc39b046567340e8e198e3944178022a08547",
          "sha1": "3026bc0d3139095006011ae05f714c00b683c6d9",
          "md5": "3429cf133210a3faea659b7d634bd7f9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-compilation-lib-tor-gpl",
          "version": {
            "requires": "409.13.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-gpl-release.aar",
          "url": "resource-lib-tor-gpl-android-409.13.0-SNAPSHOT.aar",
          "size": 28101,
          "sha512": "80bf00a48c3a776b54af83f19fa75365fa13f296a0ae495c973a3e71906c2f41e812d2c3c3d41c86f1b13fba08eef72d7e7ada312712e4f68aafcfac6360d3cd",
          "sha256": "3596fa41cbc57b86956e6d003dccc39b046567340e8e198e3944178022a08547",
          "sha1": "3026bc0d3139095006011ae05f714c00b683c6d9",
          "md5": "3429cf133210a3faea659b7d634bd7f9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-lib-tor-gpl-android-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-lib-tor-gpl-android-409.13.0-SNAPSHOT-sources.jar",
          "size": 7975,
          "sha512": "d3980939ae440cf541fd02c3162c9b907870bf68cb4eba04310ed9b17501823fd4827b2b1ae0f63ab4e822b0646d34d35e91b6160311f46cf1e63241438c3c41",
          "sha256": "04025880db2e41fa501c6f9478dadc317342f271bbd3ce0bd74c906a53742610",
          "sha1": "ea9ff99fbeff9d04aa9c1705da1818278f70deac",
          "md5": "f7cfa90b447239cd0e3dc4618f3d4f53"
        }
      ]
    }
  ]
}
