{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-lib-tor/409.13.0-SNAPSHOT/resource-lib-tor-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-lib-tor",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-jvm-409.13.0-SNAPSHOT.jar",
          "url": "resource-lib-tor-jvm-409.13.0-SNAPSHOT.jar",
          "size": 62110535,
          "sha512": "22aa6b4c18df61f242bdf29ab5ce9ffe32e6a5fbf193e29ceb3c839ea4877bbe1fb0f7b746abd672e4683d5b404442bfac738b8ebdafd292fc842fb4d2e59d60",
          "sha256": "171a968f89883a4f166f6ebb410b5f0e1acb2c94cdd522b826c1ece29aa783d8",
          "sha1": "fce323746cd70f5340b1cb479c2cc3685d740359",
          "md5": "5c747e05f81aebd306b059654ffc85a6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-jvm-409.13.0-SNAPSHOT.jar",
          "url": "resource-lib-tor-jvm-409.13.0-SNAPSHOT.jar",
          "size": 62110535,
          "sha512": "22aa6b4c18df61f242bdf29ab5ce9ffe32e6a5fbf193e29ceb3c839ea4877bbe1fb0f7b746abd672e4683d5b404442bfac738b8ebdafd292fc842fb4d2e59d60",
          "sha256": "171a968f89883a4f166f6ebb410b5f0e1acb2c94cdd522b826c1ece29aa783d8",
          "sha1": "fce323746cd70f5340b1cb479c2cc3685d740359",
          "md5": "5c747e05f81aebd306b059654ffc85a6"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "resource-lib-tor-jvm-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-lib-tor-jvm-409.13.0-SNAPSHOT-sources.jar",
          "size": 7603,
          "sha512": "ea3617cd852634643ca9644b8688f1b42e60c345d90b782ae189b2ec2ee25248f7cddcee7018708540373c67f39fc06976675c5ecbb1aaa5fd83b2fb056ac4da",
          "sha256": "037c5ef8650245eb35c1e0c18a433b5fc137422a1ed71e16a2e1e10165658e0a",
          "sha1": "b79d24163b9342df427a0963409c8c84b7fdb3d4",
          "md5": "621656b990811d80d5ec7421f32df69a"
        }
      ]
    }
  ]
}
