{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor/409.13.0-SNAPSHOT/resource-exec-tor-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-exec-tor",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-androidNativeX86Main-409.13.0-SNAPSHOT.klib",
          "url": "resource-exec-tor-androidnativex86-409.13.0-SNAPSHOT.klib",
          "size": 23788,
          "sha512": "e28f4352a4f36949adbd998ce035747b18155255652f20efce5a01ec655f9813464db37ea7429a9715c60e74623f2813006af766285a7331fa8191eabeaf5246",
          "sha256": "65d8b69c2c3cf9e74bbc30f9d781ccd12c642bb840677c425bffc82f5eebea7f",
          "sha1": "e080f6f8ebf68b048631c61cef7ff25bc357d2ad",
          "md5": "0b70c8234bbdd298692f6c01bce71406"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-exec-tor-androidnativex86-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-exec-tor-androidnativex86-409.13.0-SNAPSHOT-sources.jar",
          "size": 11711,
          "sha512": "cbc9c98a2eec49e576023f221a4c64d2f8c41624fcb727e3821163f3e5da98ec60b90ad2227c2e99798e7795ebf4859c35c3009463b1d4e97d3f7f08535af115",
          "sha256": "be928b9f248c958477cc8bc557a5c91a7da67ad01280376547e693aef6708a38",
          "sha1": "d06d3b8f277c27c1fb3689e5dc0e2f3cbc68893c",
          "md5": "f87f6530ffcc3e90e4e2a856c1ceb3cd"
        }
      ]
    }
  ]
}
