{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-android-unit-test-tor-gpl/409.13.0/resource-android-unit-test-tor-gpl-409.13.0.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-android-unit-test-tor-gpl",
    "version": "409.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-android-unit-test-tor-gpl-release.aar",
          "url": "resource-android-unit-test-tor-gpl-android-409.13.0.aar",
          "size": 62735047,
          "sha512": "66a92f0a34794e162c23e51a3d3f0a1b1b831208de836400ad75975fb7b59ba3347dbe6bfe6f41d4efc4dcbecff1f392ba04bb28b172974dfd2a3064ca7078c5",
          "sha256": "052e3b86450703224ba4c1a6f0ed30de259b180f6da8bd0e683d12d1bbbb843b",
          "sha1": "bd3bcece9502e799ab54fd8be2826d0e2a850d03",
          "md5": "ebd6c12b5185fc4e1d020ea0f0321f30"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-android-unit-test-tor-gpl-release.aar",
          "url": "resource-android-unit-test-tor-gpl-android-409.13.0.aar",
          "size": 62735047,
          "sha512": "66a92f0a34794e162c23e51a3d3f0a1b1b831208de836400ad75975fb7b59ba3347dbe6bfe6f41d4efc4dcbecff1f392ba04bb28b172974dfd2a3064ca7078c5",
          "sha256": "052e3b86450703224ba4c1a6f0ed30de259b180f6da8bd0e683d12d1bbbb843b",
          "sha1": "bd3bcece9502e799ab54fd8be2826d0e2a850d03",
          "md5": "ebd6c12b5185fc4e1d020ea0f0321f30"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-android-unit-test-tor-gpl-android-409.13.0-sources.jar",
          "url": "resource-android-unit-test-tor-gpl-android-409.13.0-sources.jar",
          "size": 2635,
          "sha512": "a1ee7f658f0314d0c2f5eac5fe77278e617f7ba233f888316a7843254b0e66eee171e68b4c426657a1c9dd3a5d8fb1d6c945811285af35ebb8a7fe4197533ee7",
          "sha256": "49113d5c3ae39ba080c49a8b6a0cb8bf0dfb9f6cb10df6d95892b83a1b380750",
          "sha1": "b0362b4dcbaa0b6dd486d1bc571586572e0a6569",
          "md5": "a01342f64298435e56d85bfea1f43da5"
        }
      ]
    }
  ]
}
