{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-lib-tor",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-metadata-409.13.0-rc1.jar",
          "url": "resource-lib-tor-409.13.0-rc1.jar",
          "size": 939,
          "sha512": "4c761bc36db2b385143c7617a689d9bd37abc1c2566dfb4d18203161508d7f1936eb2275871f21010dd168cb250c515699f216a04d8fffbf1154e5a5fa4a7b48",
          "sha256": "eed2add0452147bcf54d06f0145ed77f0ca73ce9a0cf7dfea1cb2a91f7418431",
          "sha1": "897bcf9e3a39c0c966746f2a7375bc70ed9fc4c2",
          "md5": "6704e9e5af02f87cc3e7bb980d059270"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "resource-lib-tor-kotlin-409.13.0-rc1-sources.jar",
          "url": "resource-lib-tor-409.13.0-rc1-sources.jar",
          "size": 5620,
          "sha512": "fef7b42396428eab360c5c53f11456dd95d75bfc81b6c6ce2ba810211a7b8b1c5eea6899998af62fd35164a85ab928636819027e87448f17822d322c8812ce3b",
          "sha256": "20f20cd8865a1ce0691efbcb3cf7c66fc2de7cea7c15d164e095dcc2e51d5c0a",
          "sha1": "55850dd8f6ca43e658435b246d0f53502cc03959",
          "md5": "5bc69ebdac5855d00f0b777fe897281f"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-lib-tor-android/409.13.0-rc1/resource-lib-tor-android-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-lib-tor-android",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-lib-tor-android/409.13.0-rc1/resource-lib-tor-android-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-lib-tor-android",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-lib-tor-android/409.13.0-rc1/resource-lib-tor-android-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-lib-tor-android",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-lib-tor-iossimulatorarm64/409.13.0-rc1/resource-lib-tor-iossimulatorarm64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-lib-tor-iossimulatorarm64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-lib-tor-iossimulatorarm64/409.13.0-rc1/resource-lib-tor-iossimulatorarm64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-lib-tor-iossimulatorarm64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-lib-tor-iossimulatorarm64/409.13.0-rc1/resource-lib-tor-iossimulatorarm64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-lib-tor-iossimulatorarm64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-lib-tor-iosx64/409.13.0-rc1/resource-lib-tor-iosx64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-lib-tor-iosx64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-lib-tor-iosx64/409.13.0-rc1/resource-lib-tor-iosx64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-lib-tor-iosx64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-lib-tor-iosx64/409.13.0-rc1/resource-lib-tor-iosx64-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-lib-tor-iosx64",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-lib-tor-jvm/409.13.0-rc1/resource-lib-tor-jvm-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-lib-tor-jvm",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-lib-tor-jvm/409.13.0-rc1/resource-lib-tor-jvm-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-lib-tor-jvm",
        "version": "409.13.0-rc1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-lib-tor-jvm/409.13.0-rc1/resource-lib-tor-jvm-409.13.0-rc1.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-lib-tor-jvm",
        "version": "409.13.0-rc1"
      }
    }
  ]
}
