{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-geoip/409.13.0/resource-geoip-409.13.0.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-geoip",
    "version": "409.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-geoip-androidNativeArm64Main-409.13.0.klib",
          "url": "resource-geoip-androidnativearm64-409.13.0.klib",
          "size": 9576205,
          "sha512": "0eda507e17685104a2d1224517a312768bcfd9a059bb5adf35de734f25f25511a68bd42c5091e6a9f928d39fd9433f0ecbac57ffd7309522545f442f830b2bca",
          "sha256": "3691a144993f79cb4e4f7a3b9912a6eacbde0177316b417b6c0fd8de7bafce7e",
          "sha1": "55ad0a3af0ac182580b01edc3b61e326343735c7",
          "md5": "95678d14c022caa53241403114c1c1e2"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-geoip-androidnativearm64-409.13.0-sources.jar",
          "url": "resource-geoip-androidnativearm64-409.13.0-sources.jar",
          "size": 4588753,
          "sha512": "1a513a3871b59f3542fde57e12f32b273416964b9d6967acc4e3f5e0db8af1d897de1f7b0f171cb103755c2e0ed00932ed28fefe39d79e76b5b8a476a87dc59b",
          "sha256": "c62b123bd943ffc2a84b583494584f916166b680ba857796826486bcdca8e96e",
          "sha1": "17f487177fae67faae85c16119b67e5569ed74fb",
          "md5": "c8eb36520f269f8f63662e2eab5c4610"
        }
      ]
    }
  ]
}
