{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-compilation-lib-tor-gpl/409.13.0-rc1/resource-compilation-lib-tor-gpl-409.13.0-rc1.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-compilation-lib-tor-gpl",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-compilation-lib-tor-gpl-release.aar",
          "url": "resource-compilation-lib-tor-gpl-android-409.13.0-rc1.aar",
          "size": 14834578,
          "sha512": "70b57086d88ef0f4605e4bda7cbbabd21404a1850073e09ee6c9b6dc30885e8e2ed70b72bba2d3636cefe27901bb90c4e97c006275851b7f45ec08dad80085e8",
          "sha256": "8f0f2bd5f083f5ac582ea68b2495c218a86470017c4975261ce102857c5f0b55",
          "sha1": "a87aa11ad2984ca3f5731f1196f9bfa43778eb84",
          "md5": "13a547099589a0edcb272b3e312e84b0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-compilation-lib-tor-gpl-release.aar",
          "url": "resource-compilation-lib-tor-gpl-android-409.13.0-rc1.aar",
          "size": 14834578,
          "sha512": "70b57086d88ef0f4605e4bda7cbbabd21404a1850073e09ee6c9b6dc30885e8e2ed70b72bba2d3636cefe27901bb90c4e97c006275851b7f45ec08dad80085e8",
          "sha256": "8f0f2bd5f083f5ac582ea68b2495c218a86470017c4975261ce102857c5f0b55",
          "sha1": "a87aa11ad2984ca3f5731f1196f9bfa43778eb84",
          "md5": "13a547099589a0edcb272b3e312e84b0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-compilation-lib-tor-gpl-android-409.13.0-rc1-sources.jar",
          "url": "resource-compilation-lib-tor-gpl-android-409.13.0-rc1-sources.jar",
          "size": 4033,
          "sha512": "ab98f035bebbfece927f889039fa5562cc31284547a722630244ba66f0133e8a6bbf184130ce616afd6ed3c71921e34658060cb3acad419f763d8319c5a3fb48",
          "sha256": "84ed2d37f9acd2fb20d8569eb4eaf3efdec16833ec0949ec54a37b9972097d0b",
          "sha1": "2afd79f162572ddfecb3d63627bab20f41ba3d3e",
          "md5": "b30d4ff64bd0b7b7fc7ac149264458e1"
        }
      ]
    }
  ]
}
