{
  "formatVersion": "1.1",
  "component": {
    "group": "network.bisq.kmp-tor",
    "module": "resource-geoip",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-geoip-metadata-409.13.0-SNAPSHOT.jar",
          "url": "resource-geoip-409.13.0-SNAPSHOT.jar",
          "size": 4596636,
          "sha512": "7f17decf1bf60311c48865c4047e0efb18cb960f575fd7f355fc328576ca01f51f7e0b287ff20512c6296ded0ffe97b870673e994bd11da1f6b3d0b700e78d54",
          "sha256": "730b4fada773a57d653c89eb325834487b3711c2f87935049efee9a68c03d2eb",
          "sha1": "84440649a907edaa655fad1a98c8c465974716b1",
          "md5": "d4aa02fba17d8bb40ec25347729876a5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "resource-geoip-kotlin-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-geoip-409.13.0-SNAPSHOT-sources.jar",
          "size": 4588753,
          "sha512": "600c8441d62360e3f81d994dd0936b88f42ef9bb72c01040030df2614cd86323ea1d45ba9a289191ad3c99dad6aafa2494dea347673ad7f705fd2bf3cb76667d",
          "sha256": "87e3bfa8891e8b97e03be3dc72542c6ff87c92735f196a95589802e353e7630e",
          "sha1": "2d6f0bd4e233026687500d5a6202bf5d137d6e50",
          "md5": "83b607e646d328856e5166b7454394ad"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-androidnativearm32/409.13.0-SNAPSHOT/resource-geoip-androidnativearm32-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-androidnativearm32",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-androidnativearm32/409.13.0-SNAPSHOT/resource-geoip-androidnativearm32-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-androidnativearm32",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-androidnativearm64/409.13.0-SNAPSHOT/resource-geoip-androidnativearm64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-androidnativearm64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-androidnativearm64/409.13.0-SNAPSHOT/resource-geoip-androidnativearm64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-androidnativearm64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-androidnativex64/409.13.0-SNAPSHOT/resource-geoip-androidnativex64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-androidnativex64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-androidnativex64/409.13.0-SNAPSHOT/resource-geoip-androidnativex64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-androidnativex64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-androidnativex86/409.13.0-SNAPSHOT/resource-geoip-androidnativex86-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-androidnativex86",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-androidnativex86/409.13.0-SNAPSHOT/resource-geoip-androidnativex86-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-androidnativex86",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-iosarm64/409.13.0-SNAPSHOT/resource-geoip-iosarm64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-iosarm64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-iosarm64/409.13.0-SNAPSHOT/resource-geoip-iosarm64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-iosarm64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-iosarm64/409.13.0-SNAPSHOT/resource-geoip-iosarm64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-iosarm64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-iossimulatorarm64/409.13.0-SNAPSHOT/resource-geoip-iossimulatorarm64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-iossimulatorarm64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-iossimulatorarm64/409.13.0-SNAPSHOT/resource-geoip-iossimulatorarm64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-iossimulatorarm64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-iossimulatorarm64/409.13.0-SNAPSHOT/resource-geoip-iossimulatorarm64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-iossimulatorarm64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-iosx64/409.13.0-SNAPSHOT/resource-geoip-iosx64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-iosx64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-iosx64/409.13.0-SNAPSHOT/resource-geoip-iosx64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-iosx64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-geoip-iosx64/409.13.0-SNAPSHOT/resource-geoip-iosx64-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-iosx64",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-geoip-jvm/409.13.0-SNAPSHOT/resource-geoip-jvm-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-jvm",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-geoip-jvm/409.13.0-SNAPSHOT/resource-geoip-jvm-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-jvm",
        "version": "409.13.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-geoip-jvm/409.13.0-SNAPSHOT/resource-geoip-jvm-409.13.0-SNAPSHOT.module",
        "group": "network.bisq.kmp-tor",
        "module": "resource-geoip-jvm",
        "version": "409.13.0-SNAPSHOT"
      }
    }
  ]
}
