{
  "formatVersion": "1.1",
  "component": {
    "group": "network.bisq.kmp-tor",
    "module": "resource-frameworks-gradle-plugin",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "resource-frameworks-gradle-plugin-409.13.0-SNAPSHOT.jar",
          "url": "resource-frameworks-gradle-plugin-409.13.0-SNAPSHOT.jar",
          "size": 5970682,
          "sha512": "3253082c10fba07201c737ecf76b8d73c5e044dfa4c1b7dcef7a8939ae364b5150869ea9f9fafb58595834940dc8f58cf97648b019b73907f9533cfd8ec3ab79",
          "sha256": "2a869c8c0f8749aa8d4e6f3f06d7008abf95634d92ab42270d6b8f81f7efa36e",
          "sha1": "76f1cb120060e1099555427e325f175385d4c9c8",
          "md5": "10ac7167277909c7b02d3389f7ae2425"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.encoding",
          "module": "base16",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "resource-frameworks-gradle-plugin-409.13.0-SNAPSHOT.jar",
          "url": "resource-frameworks-gradle-plugin-409.13.0-SNAPSHOT.jar",
          "size": 5970682,
          "sha512": "3253082c10fba07201c737ecf76b8d73c5e044dfa4c1b7dcef7a8939ae364b5150869ea9f9fafb58595834940dc8f58cf97648b019b73907f9533cfd8ec3ab79",
          "sha256": "2a869c8c0f8749aa8d4e6f3f06d7008abf95634d92ab42270d6b8f81f7efa36e",
          "sha1": "76f1cb120060e1099555427e325f175385d4c9c8",
          "md5": "10ac7167277909c7b02d3389f7ae2425"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resource-frameworks-gradle-plugin-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-frameworks-gradle-plugin-409.13.0-SNAPSHOT-sources.jar",
          "size": 5963310,
          "sha512": "f30df17830f4dd282c89f5b3cdef63e49ec7fffbb204aef7090ab282455baf3ae8aaf37f46346943f897ba4ff9143f8d2499663f439bc790d677835bdd7a50ee",
          "sha256": "784d6b6f565c3ba58581a25a297443049a9149c982149a168867956850000ded",
          "sha1": "6f5bde4d965991f46c4969c8e9b71b5d0c2e5313",
          "md5": "a6b74c5e3e1004236909e7d30059ac3a"
        }
      ]
    }
  ]
}
