{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-geoip/409.13.0-rc1/resource-geoip-409.13.0-rc1.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-geoip",
    "version": "409.13.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-geoip-androidNativeArm32Main-409.13.0-rc1.klib",
          "url": "resource-geoip-androidnativearm32-409.13.0-rc1.klib",
          "size": 9576205,
          "sha512": "61bee163e15162d419fc0a5632aee3aef326375a2ec9bccf757efa76a0b870a94b3b227556c0699b21fb4b6a820e2418a48a88969f0dfa8ee1e390c78b3c30e9",
          "sha256": "c611f7a179b9e7699a83264213d4084bd6c735f378299d08388d3f69eb3fb648",
          "sha1": "e5aa40ae9fd1c7b3a7fedd81a9d55c26a5015d87",
          "md5": "89ab9efc1ba14451e9fba1a556ff08c3"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-geoip-androidnativearm32-409.13.0-rc1-sources.jar",
          "url": "resource-geoip-androidnativearm32-409.13.0-rc1-sources.jar",
          "size": 4588753,
          "sha512": "1a513a3871b59f3542fde57e12f32b273416964b9d6967acc4e3f5e0db8af1d897de1f7b0f171cb103755c2e0ed00932ed28fefe39d79e76b5b8a476a87dc59b",
          "sha256": "c62b123bd943ffc2a84b583494584f916166b680ba857796826486bcdca8e96e",
          "sha1": "17f487177fae67faae85c16119b67e5569ed74fb",
          "md5": "c8eb36520f269f8f63662e2eab5c4610"
        }
      ]
    }
  ]
}
