{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-exec-tor",
    "version": "409.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-metadata-409.13.0.jar",
          "url": "resource-exec-tor-409.13.0.jar",
          "size": 19564,
          "sha512": "377876de3841d3165635c9d81a3e6d0fe48bb3ab7cd325b80aa5f9bf552d7f11f01e14f2fde7ac486c161ac7fd92fe5040e3370b1f305cd1d74c5faa42452853",
          "sha256": "3e53b656b0f34ed60c39cd0e06ba9e36fb0f0a1554a059615828dcf6a3df6953",
          "sha1": "2b593dd888010ff9383cab4abb5236e30b802c57",
          "md5": "645dde8f7b3ced0e6caf3c031ca56744"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "resource-exec-tor-kotlin-409.13.0-sources.jar",
          "url": "resource-exec-tor-409.13.0-sources.jar",
          "size": 14782,
          "sha512": "a3086aa239a657461bd310738905d907cdb1ddba6abc2579d4c128e61f6a708f570d9959bdbc4c86e1f3878eef42423805c6c3e5721137c7ceba395791e50412",
          "sha256": "0c828e2ec3a88e46146cd9ff0101429795c40639698f69f0adbe1bbd8d4917f3",
          "sha1": "8b876773b48b11e0cf0a9f51855beb18d4ca21b3",
          "md5": "05862dfe622e394f48f94b2ba16de011"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-exec-tor-android/409.13.0/resource-exec-tor-android-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-android",
        "version": "409.13.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-exec-tor-android/409.13.0/resource-exec-tor-android-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-android",
        "version": "409.13.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-exec-tor-android/409.13.0/resource-exec-tor-android-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-android",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-androidnativearm32/409.13.0/resource-exec-tor-androidnativearm32-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-androidnativearm32",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-androidnativearm32/409.13.0/resource-exec-tor-androidnativearm32-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-androidnativearm32",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-androidnativearm64/409.13.0/resource-exec-tor-androidnativearm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-androidnativearm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-androidnativearm64/409.13.0/resource-exec-tor-androidnativearm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-androidnativearm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-androidnativex64/409.13.0/resource-exec-tor-androidnativex64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-androidnativex64",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-androidnativex64/409.13.0/resource-exec-tor-androidnativex64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-androidnativex64",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-androidnativex86/409.13.0/resource-exec-tor-androidnativex86-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-androidnativex86",
        "version": "409.13.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-androidnativex86/409.13.0/resource-exec-tor-androidnativex86-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-androidnativex86",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-iosarm64/409.13.0/resource-exec-tor-iosarm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-iosarm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-iosarm64/409.13.0/resource-exec-tor-iosarm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-iosarm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-iosarm64/409.13.0/resource-exec-tor-iosarm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-iosarm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-iossimulatorarm64/409.13.0/resource-exec-tor-iossimulatorarm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-iossimulatorarm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-iossimulatorarm64/409.13.0/resource-exec-tor-iossimulatorarm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-iossimulatorarm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-iossimulatorarm64/409.13.0/resource-exec-tor-iossimulatorarm64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-iossimulatorarm64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-iosx64/409.13.0/resource-exec-tor-iosx64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-iosx64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-iosx64/409.13.0/resource-exec-tor-iosx64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-iosx64",
        "version": "409.13.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-exec-tor-iosx64/409.13.0/resource-exec-tor-iosx64-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-iosx64",
        "version": "409.13.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-exec-tor-jvm/409.13.0/resource-exec-tor-jvm-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-jvm",
        "version": "409.13.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-exec-tor-jvm/409.13.0/resource-exec-tor-jvm-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-jvm",
        "version": "409.13.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-exec-tor-jvm/409.13.0/resource-exec-tor-jvm-409.13.0.module",
        "group": "io.github.rodvar.kmp-tor",
        "module": "resource-exec-tor-jvm",
        "version": "409.13.0"
      }
    }
  ]
}
