{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-lib-tor-gpl/409.13.0-SNAPSHOT/resource-lib-tor-gpl-409.13.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-lib-tor-gpl",
    "version": "409.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-gpl-iosX64Main-409.13.0-SNAPSHOT.klib",
          "url": "resource-lib-tor-gpl-iosx64-409.13.0-SNAPSHOT.klib",
          "size": 6877925,
          "sha512": "c48f917cc17492dfedc2c5b7f673fc6c9344ad0f0a96011d64c02d661ef353740ff4266b983ea221e67ceae7131570c23b35b08b6526e0e0e12f7baa8c42ac71",
          "sha256": "597bcb46595b39b5131651ff1c782a5eb9c2ee54dbfa6b50669b208e4a1a8b71",
          "sha1": "35175ce2270fe885fdf9db17abfc64c40fa83054",
          "md5": "d396beecc56e40c6ffed8a860c0621eb"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-lib-tor-gpl-iosx64-409.13.0-SNAPSHOT-sources.jar",
          "url": "resource-lib-tor-gpl-iosx64-409.13.0-SNAPSHOT-sources.jar",
          "size": 3304619,
          "sha512": "8512a428fc4fc0040f0a5ba994dba126ce39d31c99f99426e08101b74f0b4606ce0bf7ab72846731e109d1e72d53c72598bf346eac26fa386448500b727f590f",
          "sha256": "57267ff75ebeba12ad855fd69569ca056836053ba0a1359a9e502b3aaed558da",
          "sha1": "d950ce9874031b8f2b11576d354aac12063a2483",
          "md5": "77bfa66d7e150da349d4e133afd22b4b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "resource-lib-tor-gpl-iosx64-409.13.0-SNAPSHOT-metadata.jar",
          "url": "resource-lib-tor-gpl-iosx64-409.13.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
