{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-compilation-exec-tor/409.12.0-SNAPSHOT/resource-compilation-exec-tor-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-compilation-exec-tor",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-compilation-exec-tor-release.aar",
          "url": "resource-compilation-exec-tor-android-409.12.0-SNAPSHOT.aar",
          "size": 9653,
          "sha512": "c55d26b4da69c031c421914a2b767600902083c52d771d7968c2c7132ddafe91f256a738259686b09a81ff7f21daee12ebcee37e44bb4a43df570af7ef92f43a",
          "sha256": "2118f026d60ebdbe767271e2735900d657ab5cec6704cef81baf3d8847bc891e",
          "sha1": "7964c18b81fe47e8b13c21fe4e4e12e6d7604b5a",
          "md5": "88f686cca21edc437689f029863076c0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "network.bisq.kmp-tor",
          "module": "resource-compilation-lib-tor",
          "version": {
            "requires": "409.12.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-compilation-exec-tor-release.aar",
          "url": "resource-compilation-exec-tor-android-409.12.0-SNAPSHOT.aar",
          "size": 9653,
          "sha512": "c55d26b4da69c031c421914a2b767600902083c52d771d7968c2c7132ddafe91f256a738259686b09a81ff7f21daee12ebcee37e44bb4a43df570af7ef92f43a",
          "sha256": "2118f026d60ebdbe767271e2735900d657ab5cec6704cef81baf3d8847bc891e",
          "sha1": "7964c18b81fe47e8b13c21fe4e4e12e6d7604b5a",
          "md5": "88f686cca21edc437689f029863076c0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-compilation-exec-tor-android-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-compilation-exec-tor-android-409.12.0-SNAPSHOT-sources.jar",
          "size": 3213,
          "sha512": "9db7483b258b403f36821fc9f22a1607e91394f37ff82eca6e1993ba87e0252529ac399f252ee5c2c13c7ea0cc60b12f59029c30b4f142f38b2817e087a76cbe",
          "sha256": "5614b2c29b287cbdfcb62c19eb5aadf523154ed01dd85cfd0724938172e8060a",
          "sha1": "ce7e37fa23fc6d6a8d142894a9c442832b720158",
          "md5": "9017018508a71ad2ff0dd848ebb2beee"
        }
      ]
    }
  ]
}
