{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-exec-tor-gpl/409.13.0/resource-exec-tor-gpl-409.13.0.module",
    "group": "io.github.rodvar.kmp-tor",
    "module": "resource-exec-tor-gpl",
    "version": "409.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-api",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.matthewnelson.kmp-tor",
          "module": "common-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "io.github.rodvar.kmp-tor",
          "module": "resource-geoip",
          "version": {
            "requires": "409.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "resource-exec-tor-gpl-androidNativeX86Main-409.13.0.klib",
          "url": "resource-exec-tor-gpl-androidnativex86-409.13.0.klib",
          "size": 23801,
          "sha512": "96cb8967df93d8a34f7422c31318c17e7d5985089a64758d218f7bcc9e170da195afd30b703d67b53468cf1d8790f8a7e990392ce885624076f4ff65ff38ab7d",
          "sha256": "b7e83a8338e891be9ee24b70f66790d70f3b7fc485c9d4854b0cddc07585c801",
          "sha1": "a998b5ff5bcddf75e3e66c25295d459af1009439",
          "md5": "9ac99b5817793da2695b55dafd1329e4"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resource-exec-tor-gpl-androidnativex86-409.13.0-sources.jar",
          "url": "resource-exec-tor-gpl-androidnativex86-409.13.0-sources.jar",
          "size": 11711,
          "sha512": "cbc9c98a2eec49e576023f221a4c64d2f8c41624fcb727e3821163f3e5da98ec60b90ad2227c2e99798e7795ebf4859c35c3009463b1d4e97d3f7f08535af115",
          "sha256": "be928b9f248c958477cc8bc557a5c91a7da67ad01280376547e693aef6708a38",
          "sha1": "d06d3b8f277c27c1fb3689e5dc0e2f3cbc68893c",
          "md5": "f87f6530ffcc3e90e4e2a856c1ceb3cd"
        }
      ]
    }
  ]
}
