{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource-android-unit-test-tor/409.12.0-SNAPSHOT/resource-android-unit-test-tor-409.12.0-SNAPSHOT.module",
    "group": "network.bisq.kmp-tor",
    "module": "resource-android-unit-test-tor",
    "version": "409.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-android-unit-test-tor-release.aar",
          "url": "resource-android-unit-test-tor-android-409.12.0-SNAPSHOT.aar",
          "size": 62289991,
          "sha512": "23b575754ea88168c254164bb32afb8be743325e19d5cc557d18bd5a38c052d83424d10eed8513261baed1000a2275a2d62a7fc140da556424e4b3d04cf76f12",
          "sha256": "85c33d126df1eee77a2c93af5e45cd21896563067e9f41ab11ff8306d65339df",
          "sha1": "596070e3cef2e49d4535bf3be4af85308b66d5cc",
          "md5": "a3933dd236e3198a38f5655c87ad0f37"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resource-android-unit-test-tor-release.aar",
          "url": "resource-android-unit-test-tor-android-409.12.0-SNAPSHOT.aar",
          "size": 62289991,
          "sha512": "23b575754ea88168c254164bb32afb8be743325e19d5cc557d18bd5a38c052d83424d10eed8513261baed1000a2275a2d62a7fc140da556424e4b3d04cf76f12",
          "sha256": "85c33d126df1eee77a2c93af5e45cd21896563067e9f41ab11ff8306d65339df",
          "sha1": "596070e3cef2e49d4535bf3be4af85308b66d5cc",
          "md5": "a3933dd236e3198a38f5655c87ad0f37"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resource-android-unit-test-tor-android-409.12.0-SNAPSHOT-sources.jar",
          "url": "resource-android-unit-test-tor-android-409.12.0-SNAPSHOT-sources.jar",
          "size": 2635,
          "sha512": "a1ee7f658f0314d0c2f5eac5fe77278e617f7ba233f888316a7843254b0e66eee171e68b4c426657a1c9dd3a5d8fb1d6c945811285af35ebb8a7fe4197533ee7",
          "sha256": "49113d5c3ae39ba080c49a8b6a0cb8bf0dfb9f6cb10df6d95892b83a1b380750",
          "sha1": "b0362b4dcbaa0b6dd486d1bc571586572e0a6569",
          "md5": "a01342f64298435e56d85bfea1f43da5"
        }
      ]
    }
  ]
}
